/* ============================================================
   ŠICHTA — preklady
   Ak chceš niečo opraviť, meň len text v úvodzovkách.
   Kľúče vľavo (napr. arrive:) nechaj tak, appka ich hľadá podľa nich.
   'cur' je značka meny — zmeň, ak prevádzka platí v inej.
   ============================================================ */
window.LANGS = {

/* ---------------- SLOVENČINA ---------------- */
sk:{ label:'Slovenčina', locale:'sk-SK', cur:'€',
  dows:['Po','Ut','St','Št','Pi','So','Ne'],
  months:['Január','Február','Marec','Apríl','Máj','Jún','Júl','August','September','Október','November','December'],
  dayNames:['Nedeľa','Pondelok','Utorok','Streda','Štvrtok','Piatok','Sobota'],
  tagline:'Evidencia zmien a dochádzky', language:'Jazyk',
  owner:'Vlastník', employee:'Zamestnanec', imEmployee:'Som zamestnanec', imOwner:'Som vlastník',
  email:'E-mail', password:'Heslo', signin:'Prihlásiť sa', signout:'Odhlásiť',
  code:'Kód zamestnanca', enter:'Vstúpiť', demoEnter:'Vyskúšať demo',
  demoNote:'Demo režim: dáta sú len v pamäti a po obnovení stránky sa vrátia na začiatok.',
  liveNote:'Pripojené na databázu.',
  badLogin:'Nesprávny e-mail alebo heslo.', badCode:'Taký kód neexistuje.',
  tabToday:'Dnes', tabPlan2:'Plán', tabHist:'História', tabPeople:'Ľudia',
  details:'Podrobnosti',
  atWork:'V práci', hoursToday:'Hodín dnes', costToday:'Náklad dnes',
  atWorkNames:'V práci', nobodyAtWork:'Nikto nie je v práci',
  arrive:'Príchod', leave:'Odchod', arrived:'Príchod', left:'Odchod',
  atWorkSince:'V práci od', shiftNotStarted:'Zmena ešte nezačala', doneLbl:'Hotovo',
  breakStart:'Prestávka', breakEnd:'Koniec prestávky', onBreakSince:'Na prestávke od',
  breaksLbl:'Prestávky', breakTotal:'Prestávky spolu', noBreaks:'Žiadne prestávky',
  addBreak:'Pridať prestávku', netWorked:'Čistý čas', grossTime:'Na pracovisku',
  recorded:'Zapísané', undo:'Vrátiť', fix:'Opraviť', fixTimes:'Opraviť čas',
  fixHelp:'Ak sa zabudlo kliknúť, prepíš čas tu.', clearDeparture:'Zmazať odchod',
  total:'Spolu', hours:'Hodiny', cost:'Mzdový náklad', monthTotal:'Mesiac celkom',
  noRecord:'Žiadny záznam', legendHours:'Čísla v dňoch = odpracované hodiny všetkých spolu',
  hUnit:'h', minUnit:'min',
  thisWeek:'Tento týždeň', lastWeek:'Minulý týždeň', nextWeek:'Ďalší týždeň',
  todayChip:'DNES', nobody:'nikto', planLbl:'Plán', workedLbl:'Odpracované',
  tapDay:'Ťukni na deň a uprav ho', removeShift:'Odobrať',
  planShift:'Naplánovať zmenu', addShift:'Pridať zmenu', noShifts:'Žiadne zmeny',
  noShiftsToday:'Na dnes nie je naplánovaná žiadna zmena.',
  whichShift:'Ktorá zmena?', morningS:'Ranná', afternoonS:'Poobedná', eveningS:'Večerná', otherTime:'Iný čas',
  person:'Zamestnanec', date:'Dátum', from:'Od', to:'Do',
  addPerson:'Pridať zamestnanca', name:'Meno', rate:'Hodinová mzda', noPeople:'Ešte nemáš žiadnych zamestnancov.',
  confirmRemovePerson:'Odstrániť tohto zamestnanca aj s jeho zmenami?',
  lastLogin:'Naposledy prihlásený', neverLoggedIn:'Zatiaľ sa neprihlásil', loggedInNow:'Prihlásený teraz',
  loginsTitle:'Prihlásenia zamestnancov', codeLbl:'Kód',
  myShifts:'Moje zmeny', myHours:'Moje hodiny', gross:'Brutto',
  remove:'Odstrániť', cancel:'Zrušiť', save:'Uložiť',
  saved:'Uložené', added:'Pridané', removed:'Odstránené',
  nameRequired:'Zadaj meno.', pickPerson:'Vyber zamestnanca.', badTime:'Odchod musí byť po príchode.',
  tooLong:'Zmena by mala 16+ hodín — skontroluj čas.',
  plannedTime:'Plánovaný čas',
  breakDetail:'Prestávky (od – do)',
  changePerson:'Zmeniť človeka',
  whoRecords:'Kto zapisuje príchody',
  modeOwner:'Len ja',
  modeSelf:'Aj zamestnanci sami',
  modeHint:'Pri „Len ja“ klikáš príchody a odchody ty. Pri druhej možnosti si ich zapisuje každý sám vo svojom telefóne.',
  readOnlyNote:'Príchody zapisuje vlastník',
  todayLbl:'Dnes',
  unplanned:'Bez plánu',
  notScheduled:'Dnes nie sú v rozvrhu',
  startNow:'Príchod teraz',
  alreadyOn:'Už je v práci',
  planWeek:'Naplánovať týždeň',
  pickDays:'Ktoré dni?',
  noDays:'Vyber aspoň jeden deň.',
  createdN:'Naplánované zmeny: ',
  allHaveShift:'Všetci už zmenu majú',
  badBreak:'Prestávka musí byť v rámci zmeny.',
  signUp:'Vytvoriť účet', backToSignin:'Späť na prihlásenie',
  noAccountYet:'Nemáš ešte účet?', haveAccountYet:'Už máš účet?',
  confirmPass:'Heslo znova', passMismatch:'Heslá sa nezhodujú.',
  passTooShort:'Heslo musí mať aspoň 6 znakov.',
  checkEmailTitle:'Skontroluj e-mail',
  checkEmailMsg:'Poslali sme potvrdzovací odkaz na tvoj e-mail. Klikni naň a potom sa prihlás.',
  joinTitle:'Pripájaš sa k tímu', joinName:'Tvoje meno', joinBtn:'Pripojiť sa',
  joinBadCode:'Tento pozývací odkaz už neplatí. Popýtaj majiteľa o nový.',
  joinDone:'Hotovo, si pripojený/á!',
  inviteHint:'Zdieľaj tento odkaz s novým človekom – pridá sa sám, nemusíš ho zapisovať ručne.',
  copyLink:'Kopírovať odkaz', linkCopied:'Odkaz skopírovaný', newInviteCode:'Nový kód',
  regenConfirm:'Vygenerovať nový pozývací odkaz? Starý prestane fungovať.',
  reconnecting:'Obnovujem spojenie…',
  unclosedShifts:'Nezavreté zmeny z minulosti', unclosedSince:'nezavretá od'
},

/* ---------------- ČEŠTINA ---------------- */
cs:{ label:'Čeština', locale:'cs-CZ', cur:'Kč',
  dows:['Po','Út','St','Čt','Pá','So','Ne'],
  months:['Leden','Únor','Březen','Duben','Květen','Červen','Červenec','Srpen','Září','Říjen','Listopad','Prosinec'],
  dayNames:['Neděle','Pondělí','Úterý','Středa','Čtvrtek','Pátek','Sobota'],
  tagline:'Evidence směn a příchodů', language:'Jazyk',
  owner:'Vlastník', employee:'Zaměstnanec', imEmployee:'Jsem zaměstnanec', imOwner:'Jsem vlastník',
  email:'E-mail', password:'Heslo', signin:'Přihlásit se', signout:'Odhlásit',
  code:'Kód zaměstnance', enter:'Vstoupit', demoEnter:'Vyzkoušet demo',
  demoNote:'Demo režim: data jsou jen v paměti a po obnovení stránky se vrátí na začátek.',
  liveNote:'Připojeno k databázi.',
  badLogin:'Nesprávný e-mail nebo heslo.', badCode:'Takový kód neexistuje.',
  tabToday:'Dnes', tabPlan2:'Plán', tabHist:'Historie', tabPeople:'Lidé',
  details:'Podrobnosti',
  atWork:'V práci', hoursToday:'Hodin dnes', costToday:'Náklad dnes',
  atWorkNames:'V práci', nobodyAtWork:'Nikdo není v práci',
  arrive:'Příchod', leave:'Odchod', arrived:'Příchod', left:'Odchod',
  atWorkSince:'V práci od', shiftNotStarted:'Směna ještě nezačala', doneLbl:'Hotovo',
  breakStart:'Pauza', breakEnd:'Konec pauzy', onBreakSince:'Na pauze od',
  breaksLbl:'Pauzy', breakTotal:'Pauzy celkem', noBreaks:'Žádné pauzy',
  addBreak:'Přidat pauzu', netWorked:'Čistý čas', grossTime:'Na pracovišti',
  recorded:'Zapsáno', undo:'Vrátit', fix:'Opravit', fixTimes:'Opravit čas',
  fixHelp:'Pokud se zapomnělo kliknout, přepiš čas tady.', clearDeparture:'Smazat odchod',
  total:'Celkem', hours:'Hodiny', cost:'Mzdový náklad', monthTotal:'Měsíc celkem',
  noRecord:'Žádný záznam', legendHours:'Čísla ve dnech = odpracované hodiny všech dohromady',
  hUnit:'h', minUnit:'min',
  thisWeek:'Tento týden', lastWeek:'Minulý týden', nextWeek:'Další týden',
  todayChip:'DNES', nobody:'nikdo', planLbl:'Plán', workedLbl:'Odpracováno',
  tapDay:'Klepni na den a uprav ho', removeShift:'Odebrat',
  planShift:'Naplánovat směnu', addShift:'Přidat směnu', noShifts:'Žádné směny',
  noShiftsToday:'Na dnes není naplánovaná žádná směna.',
  whichShift:'Která směna?', morningS:'Ranní', afternoonS:'Odpolední', eveningS:'Večerní', otherTime:'Jiný čas',
  person:'Zaměstnanec', date:'Datum', from:'Od', to:'Do',
  addPerson:'Přidat zaměstnance', name:'Jméno', rate:'Hodinová mzda', noPeople:'Ještě nemáš žádné zaměstnance.',
  confirmRemovePerson:'Odstranit tohoto zaměstnance i s jeho směnami?',
  lastLogin:'Naposledy přihlášen', neverLoggedIn:'Zatím se nepřihlásil', loggedInNow:'Přihlášen nyní',
  loginsTitle:'Přihlášení zaměstnanců', codeLbl:'Kód',
  myShifts:'Moje směny', myHours:'Moje hodiny', gross:'Brutto',
  remove:'Odstranit', cancel:'Zrušit', save:'Uložit',
  saved:'Uloženo', added:'Přidáno', removed:'Odstraněno',
  nameRequired:'Zadej jméno.', pickPerson:'Vyber zaměstnance.', badTime:'Odchod musí být po příchodu.',
  tooLong:'Směna by měla 16+ hodin — zkontroluj čas.',
  plannedTime:'Plánovaný čas',
  breakDetail:'Pauzy (od – do)',
  changePerson:'Změnit člověka',
  whoRecords:'Kdo zapisuje příchody',
  modeOwner:'Jen já',
  modeSelf:'I zaměstnanci sami',
  modeHint:'U „Jen já“ klikáš příchody a odchody ty. U druhé možnosti si je zapisuje každý sám ve svém telefonu.',
  readOnlyNote:'Příchody zapisuje vlastník',
  todayLbl:'Dnes',
  unplanned:'Bez plánu',
  notScheduled:'Dnes nejsou v rozvrhu',
  startNow:'Příchod teď',
  alreadyOn:'Už je v práci',
  planWeek:'Naplánovat týden',
  pickDays:'Které dny?',
  noDays:'Vyber aspoň jeden den.',
  createdN:'Naplánované směny: ',
  allHaveShift:'Všichni už směnu mají',
  badBreak:'Pauza musí být v rámci směny.',
  signUp:'Vytvořit účet', backToSignin:'Zpět na přihlášení',
  noAccountYet:'Ještě nemáš účet?', haveAccountYet:'Už máš účet?',
  confirmPass:'Heslo znovu', passMismatch:'Hesla se neshodují.',
  passTooShort:'Heslo musí mít alespoň 6 znaků.',
  checkEmailTitle:'Zkontroluj e-mail',
  checkEmailMsg:'Poslali jsme potvrzovací odkaz na tvůj e-mail. Klikni na něj a pak se přihlas.',
  joinTitle:'Připojuješ se k týmu', joinName:'Tvoje jméno', joinBtn:'Připojit se',
  joinBadCode:'Tento zvací odkaz už neplatí. Popros majitele o nový.',
  joinDone:'Hotovo, jsi připojen/a!',
  inviteHint:'Sdílej tento odkaz s novým člověkem – přidá se sám, nemusíš ho zapisovat ručně.',
  copyLink:'Kopírovat odkaz', linkCopied:'Odkaz zkopírován', newInviteCode:'Nový kód',
  regenConfirm:'Vygenerovat nový zvací odkaz? Starý přestane fungovat.',
  reconnecting:'Obnovuji spojení…',
  unclosedShifts:'Nezavřené směny z minulosti', unclosedSince:'nezavřená od'
},

/* ---------------- POLSKI ---------------- */
pl:{ label:'Polski', locale:'pl-PL', cur:'zł',
  dows:['Pn','Wt','Śr','Cz','Pt','So','Nd'],
  months:['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'],
  dayNames:['Niedziela','Poniedziałek','Wtorek','Środa','Czwartek','Piątek','Sobota'],
  tagline:'Ewidencja zmian i obecności', language:'Język',
  owner:'Właściciel', employee:'Pracownik', imEmployee:'Jestem pracownikiem', imOwner:'Jestem właścicielem',
  email:'E-mail', password:'Hasło', signin:'Zaloguj się', signout:'Wyloguj',
  code:'Kod pracownika', enter:'Wejdź', demoEnter:'Wypróbuj demo',
  demoNote:'Tryb demo: dane są tylko w pamięci i po odświeżeniu strony wracają do początku.',
  liveNote:'Połączono z bazą danych.',
  badLogin:'Nieprawidłowy e-mail lub hasło.', badCode:'Taki kod nie istnieje.',
  tabToday:'Dziś', tabPlan2:'Plan', tabHist:'Historia', tabPeople:'Ludzie',
  details:'Szczegóły',
  atWork:'W pracy', hoursToday:'Godzin dziś', costToday:'Koszt dziś',
  atWorkNames:'W pracy', nobodyAtWork:'Nikogo nie ma w pracy',
  arrive:'Wejście', leave:'Wyjście', arrived:'Wejście', left:'Wyjście',
  atWorkSince:'W pracy od', shiftNotStarted:'Zmiana jeszcze nie zaczęła się', doneLbl:'Gotowe',
  breakStart:'Przerwa', breakEnd:'Koniec przerwy', onBreakSince:'Na przerwie od',
  breaksLbl:'Przerwy', breakTotal:'Przerwy razem', noBreaks:'Brak przerw',
  addBreak:'Dodaj przerwę', netWorked:'Czas netto', grossTime:'W pracy łącznie',
  recorded:'Zapisano', undo:'Cofnij', fix:'Popraw', fixTimes:'Popraw czas',
  fixHelp:'Jeśli zapomniano kliknąć, popraw czas tutaj.', clearDeparture:'Usuń wyjście',
  total:'Razem', hours:'Godziny', cost:'Koszt wynagrodzeń', monthTotal:'Miesiąc razem',
  noRecord:'Brak zapisu', legendHours:'Liczby w dniach = przepracowane godziny wszystkich razem',
  hUnit:'godz.', minUnit:'min',
  thisWeek:'Ten tydzień', lastWeek:'Poprzedni tydzień', nextWeek:'Następny tydzień',
  todayChip:'DZIŚ', nobody:'nikt', planLbl:'Plan', workedLbl:'Przepracowano',
  tapDay:'Dotknij dzień, aby go zmienić', removeShift:'Usuń',
  planShift:'Zaplanuj zmianę', addShift:'Dodaj zmianę', noShifts:'Brak zmian',
  noShiftsToday:'Na dziś nie zaplanowano żadnej zmiany.',
  whichShift:'Która zmiana?', morningS:'Ranna', afternoonS:'Popołudniowa', eveningS:'Wieczorna', otherTime:'Inna godzina',
  person:'Pracownik', date:'Data', from:'Od', to:'Do',
  addPerson:'Dodaj pracownika', name:'Imię', rate:'Stawka godzinowa', noPeople:'Nie masz jeszcze pracowników.',
  confirmRemovePerson:'Usunąć tego pracownika razem z jego zmianami?',
  lastLogin:'Ostatnie logowanie', neverLoggedIn:'Jeszcze się nie logował', loggedInNow:'Zalogowany teraz',
  loginsTitle:'Logowania pracowników', codeLbl:'Kod',
  myShifts:'Moje zmiany', myHours:'Moje godziny', gross:'Brutto',
  remove:'Usuń', cancel:'Anuluj', save:'Zapisz',
  saved:'Zapisano', added:'Dodano', removed:'Usunięto',
  nameRequired:'Podaj imię.', pickPerson:'Wybierz pracownika.', badTime:'Wyjście musi być po wejściu.',
  tooLong:'Zmiana miałaby 16+ godzin — sprawdź godziny.',
  plannedTime:'Planowana godzina',
  breakDetail:'Przerwy (od – do)',
  changePerson:'Zmień osobę',
  whoRecords:'Kto zapisuje wejścia',
  modeOwner:'Tylko ja',
  modeSelf:'Także pracownicy sami',
  modeHint:'Przy „Tylko ja” wejścia i wyjścia klikasz Ty. Przy drugiej opcji każdy zapisuje je sam w swoim telefonie.',
  readOnlyNote:'Wejścia zapisuje właściciel',
  todayLbl:'Dziś',
  unplanned:'Bez planu',
  notScheduled:'Dziś nie ma ich w grafiku',
  startNow:'Wejście teraz',
  alreadyOn:'Już jest w pracy',
  planWeek:'Zaplanuj tydzień',
  pickDays:'Które dni?',
  noDays:'Wybierz co najmniej jeden dzień.',
  createdN:'Zaplanowane zmiany: ',
  allHaveShift:'Wszyscy już mają zmianę',
  badBreak:'Przerwa musi mieścić się w zmianie.',
  signUp:'Utwórz konto', backToSignin:'Powrót do logowania',
  noAccountYet:'Nie masz jeszcze konta?', haveAccountYet:'Masz już konto?',
  confirmPass:'Powtórz hasło', passMismatch:'Hasła się nie zgadzają.',
  passTooShort:'Hasło musi mieć co najmniej 6 znaków.',
  checkEmailTitle:'Sprawdź e-mail',
  checkEmailMsg:'Wysłaliśmy link potwierdzający na Twój e-mail. Kliknij go, a potem się zaloguj.',
  joinTitle:'Dołączasz do zespołu', joinName:'Twoje imię', joinBtn:'Dołącz',
  joinBadCode:'Ten link zaproszenia już nie działa. Poproś właściciela o nowy.',
  joinDone:'Gotowe, jesteś dołączony/a!',
  inviteHint:'Udostępnij ten link nowej osobie – dołączy się sama, nie musisz jej dodawać ręcznie.',
  copyLink:'Kopiuj link', linkCopied:'Link skopiowany', newInviteCode:'Nowy kod',
  regenConfirm:'Wygenerować nowy link zaproszenia? Stary przestanie działać.',
  reconnecting:'Wznawiam połączenie…',
  unclosedShifts:'Niezamknięte zmiany z przeszłości', unclosedSince:'niezamknięta od'
},

/* ---------------- MAGYAR ---------------- */
hu:{ label:'Magyar', locale:'hu-HU', cur:'Ft',
  dows:['H','K','Sze','Cs','P','Szo','V'],
  months:['Január','Február','Március','Április','Május','Június','Július','Augusztus','Szeptember','Október','November','December'],
  dayNames:['Vasárnap','Hétfő','Kedd','Szerda','Csütörtök','Péntek','Szombat'],
  tagline:'Beosztás és jelenlét nyilvántartás', language:'Nyelv',
  owner:'Tulajdonos', employee:'Munkatárs', imEmployee:'Munkatárs vagyok', imOwner:'Tulajdonos vagyok',
  email:'E-mail', password:'Jelszó', signin:'Bejelentkezés', signout:'Kilépés',
  code:'Munkatárs kódja', enter:'Belépés', demoEnter:'Demó kipróbálása',
  demoNote:'Demó mód: az adatok csak a memóriában vannak, az oldal újratöltésekor visszaállnak.',
  liveNote:'Kapcsolódva az adatbázishoz.',
  badLogin:'Hibás e-mail vagy jelszó.', badCode:'Ilyen kód nem létezik.',
  tabToday:'Ma', tabPlan2:'Beosztás', tabHist:'Előzmények', tabPeople:'Emberek',
  details:'Részletek',
  atWork:'Munkában', hoursToday:'Mai órák', costToday:'Mai költség',
  atWorkNames:'Munkában', nobodyAtWork:'Senki nincs munkában',
  arrive:'Érkezés', leave:'Elmenés', arrived:'Érkezés', left:'Elmenés',
  atWorkSince:'Munkában ettől', shiftNotStarted:'A műszak még nem kezdődött el', doneLbl:'Kész',
  breakStart:'Szünet', breakEnd:'Szünet vége', onBreakSince:'Szüneten ettől',
  breaksLbl:'Szünetek', breakTotal:'Szünetek összesen', noBreaks:'Nincs szünet',
  addBreak:'Szünet hozzáadása', netWorked:'Nettó idő', grossTime:'Munkahelyen töltött',
  recorded:'Rögzítve', undo:'Visszavonás', fix:'Javítás', fixTimes:'Idő javítása',
  fixHelp:'Ha elmaradt a kattintás, itt írd át az időt.', clearDeparture:'Elmenés törlése',
  total:'Összesen', hours:'Órák', cost:'Bérköltség', monthTotal:'Hónap összesen',
  noRecord:'Nincs bejegyzés', legendHours:'A napokban lévő számok = mindenki ledolgozott órái',
  hUnit:'ó', minUnit:'p',
  thisWeek:'Ez a hét', lastWeek:'Előző hét', nextWeek:'Következő hét',
  todayChip:'MA', nobody:'senki', planLbl:'Terv', workedLbl:'Ledolgozva',
  tapDay:'Koppints egy napra a szerkesztéshez', removeShift:'Eltávolítás',
  planShift:'Műszak beosztása', addShift:'Műszak hozzáadása', noShifts:'Nincs műszak',
  noShiftsToday:'Ma nincs beosztott műszak.',
  whichShift:'Melyik műszak?', morningS:'Reggeli', afternoonS:'Délutáni', eveningS:'Esti', otherTime:'Más időpont',
  person:'Munkatárs', date:'Dátum', from:'Ettől', to:'Eddig',
  addPerson:'Munkatárs hozzáadása', name:'Név', rate:'Órabér', noPeople:'Még nincs egy munkatársad sem.',
  confirmRemovePerson:'Törlöd ezt a munkatársat a műszakjaival együtt?',
  lastLogin:'Utolsó belépés', neverLoggedIn:'Még nem lépett be', loggedInNow:'Most bejelentkezve',
  loginsTitle:'Munkatársak belépései', codeLbl:'Kód',
  myShifts:'Műszakjaim', myHours:'Óráim', gross:'Bruttó',
  remove:'Törlés', cancel:'Mégse', save:'Mentés',
  saved:'Mentve', added:'Hozzáadva', removed:'Törölve',
  nameRequired:'Add meg a nevet.', pickPerson:'Válassz munkatársat.', badTime:'Az elmenés az érkezés után legyen.',
  tooLong:'A műszak 16+ óra lenne — ellenőrizd az időt.',
  plannedTime:'Tervezett idő',
  breakDetail:'Szünetek (-tól -ig)',
  changePerson:'Személy módosítása',
  whoRecords:'Ki rögzíti az érkezéseket',
  modeOwner:'Csak én',
  modeSelf:'A munkatársak is maguk',
  modeHint:'A „Csak én” esetén te rögzíted az érkezést és elmenést. A másik lehetőségnél mindenki maga rögzíti a saját telefonján.',
  readOnlyNote:'Az érkezéseket a tulajdonos rögzíti',
  todayLbl:'Ma',
  unplanned:'Terv nélkül',
  notScheduled:'Ma nincsenek beosztva',
  startNow:'Érkezés most',
  alreadyOn:'Már munkában van',
  planWeek:'Hét beosztása',
  pickDays:'Mely napok?',
  noDays:'Válassz legalább egy napot.',
  createdN:'Beosztott műszakok: ',
  allHaveShift:'Mindenkinek van már műszakja',
  badBreak:'A szünetnek a műszakon belül kell lennie.',
  signUp:'Fiók létrehozása', backToSignin:'Vissza a bejelentkezéshez',
  noAccountYet:'Még nincs fiókod?', haveAccountYet:'Már van fiókod?',
  confirmPass:'Jelszó újra', passMismatch:'A jelszavak nem egyeznek.',
  passTooShort:'A jelszónak legalább 6 karakternek kell lennie.',
  checkEmailTitle:'Nézd meg az e-mailed',
  checkEmailMsg:'Küldtünk egy megerősítő linket az e-mail címedre. Kattints rá, majd jelentkezz be.',
  joinTitle:'Csatlakozol a csapathoz', joinName:'A neved', joinBtn:'Csatlakozás',
  joinBadCode:'Ez a meghívó link már nem érvényes. Kérj újat a tulajdonostól.',
  joinDone:'Kész, csatlakoztál!',
  inviteHint:'Oszd meg ezt a linket az új emberrel – magától csatlakozik, nem kell kézzel hozzáadnod.',
  copyLink:'Link másolása', linkCopied:'Link másolva', newInviteCode:'Új kód',
  regenConfirm:'Új meghívó linket generálunk? A régi megszűnik működni.',
  reconnecting:'Kapcsolat helyreállítása…',
  unclosedShifts:'Lezáratlan műszakok a múltból', unclosedSince:'lezáratlan ekkortól:'
},

/* ---------------- DEUTSCH ---------------- */
de:{ label:'Deutsch', locale:'de-DE', cur:'€',
  dows:['Mo','Di','Mi','Do','Fr','Sa','So'],
  months:['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
  dayNames:['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
  tagline:'Schicht- und Anwesenheitserfassung', language:'Sprache',
  owner:'Inhaber', employee:'Mitarbeiter', imEmployee:'Ich bin Mitarbeiter', imOwner:'Ich bin Inhaber',
  email:'E-Mail', password:'Passwort', signin:'Anmelden', signout:'Abmelden',
  code:'Mitarbeiter-Code', enter:'Weiter', demoEnter:'Demo testen',
  demoNote:'Demo-Modus: Daten liegen nur im Speicher und werden beim Neuladen zurückgesetzt.',
  liveNote:'Mit Datenbank verbunden.',
  badLogin:'E-Mail oder Passwort falsch.', badCode:'Diesen Code gibt es nicht.',
  tabToday:'Heute', tabPlan2:'Plan', tabHist:'Verlauf', tabPeople:'Leute',
  details:'Details',
  atWork:'Im Dienst', hoursToday:'Stunden heute', costToday:'Kosten heute',
  atWorkNames:'Im Dienst', nobodyAtWork:'Niemand ist im Dienst',
  arrive:'Kommen', leave:'Gehen', arrived:'Kommen', left:'Gehen',
  atWorkSince:'Im Dienst seit', shiftNotStarted:'Schicht hat noch nicht begonnen', doneLbl:'Fertig',
  breakStart:'Pause', breakEnd:'Pause beenden', onBreakSince:'In Pause seit',
  breaksLbl:'Pausen', breakTotal:'Pausen gesamt', noBreaks:'Keine Pausen',
  addBreak:'Pause hinzufügen', netWorked:'Nettozeit', grossTime:'Anwesend',
  recorded:'Erfasst', undo:'Rückgängig', fix:'Korrigieren', fixTimes:'Zeit korrigieren',
  fixHelp:'Falls das Klicken vergessen wurde, hier die Zeit überschreiben.', clearDeparture:'Gehen löschen',
  total:'Gesamt', hours:'Stunden', cost:'Lohnkosten', monthTotal:'Monat gesamt',
  noRecord:'Kein Eintrag', legendHours:'Zahlen in den Tagen = geleistete Stunden aller zusammen',
  hUnit:'Std.', minUnit:'Min.',
  thisWeek:'Diese Woche', lastWeek:'Letzte Woche', nextWeek:'Nächste Woche',
  todayChip:'HEUTE', nobody:'niemand', planLbl:'Plan', workedLbl:'Gearbeitet',
  tapDay:'Tippe auf einen Tag, um ihn zu ändern', removeShift:'Entfernen',
  planShift:'Schicht planen', addShift:'Schicht hinzufügen', noShifts:'Keine Schichten',
  noShiftsToday:'Für heute ist keine Schicht geplant.',
  whichShift:'Welche Schicht?', morningS:'Früh', afternoonS:'Mittag', eveningS:'Abend', otherTime:'Andere Zeit',
  person:'Mitarbeiter', date:'Datum', from:'Von', to:'Bis',
  addPerson:'Mitarbeiter hinzufügen', name:'Name', rate:'Stundenlohn', noPeople:'Du hast noch keine Mitarbeiter.',
  confirmRemovePerson:'Diesen Mitarbeiter samt Schichten entfernen?',
  lastLogin:'Zuletzt angemeldet', neverLoggedIn:'Noch nie angemeldet', loggedInNow:'Jetzt angemeldet',
  loginsTitle:'Anmeldungen der Mitarbeiter', codeLbl:'Code',
  myShifts:'Meine Schichten', myHours:'Meine Stunden', gross:'Brutto',
  remove:'Entfernen', cancel:'Abbrechen', save:'Speichern',
  saved:'Gespeichert', added:'Hinzugefügt', removed:'Entfernt',
  nameRequired:'Name eingeben.', pickPerson:'Mitarbeiter wählen.', badTime:'Gehen muss nach Kommen liegen.',
  tooLong:'Die Schicht wäre über 16 Stunden lang — Zeit prüfen.',
  plannedTime:'Geplante Zeit',
  breakDetail:'Pausen (von – bis)',
  changePerson:'Person ändern',
  whoRecords:'Wer erfasst die Zeiten',
  modeOwner:'Nur ich',
  modeSelf:'Auch die Mitarbeiter selbst',
  modeHint:'Bei „Nur ich“ erfasst du Kommen und Gehen. Bei der zweiten Option erfasst es jeder selbst auf seinem Handy.',
  readOnlyNote:'Die Zeiten erfasst der Inhaber',
  todayLbl:'Heute',
  unplanned:'Ohne Plan',
  notScheduled:'Heute nicht eingeplant',
  startNow:'Jetzt kommen',
  alreadyOn:'Ist bereits im Dienst',
  planWeek:'Woche planen',
  pickDays:'Welche Tage?',
  noDays:'Wähle mindestens einen Tag.',
  createdN:'Geplante Schichten: ',
  allHaveShift:'Alle haben schon eine Schicht',
  badBreak:'Die Pause muss innerhalb der Schicht liegen.',
  signUp:'Konto erstellen', backToSignin:'Zurück zur Anmeldung',
  noAccountYet:'Noch kein Konto?', haveAccountYet:'Schon ein Konto?',
  confirmPass:'Passwort wiederholen', passMismatch:'Die Passwörter stimmen nicht überein.',
  passTooShort:'Das Passwort muss mindestens 6 Zeichen haben.',
  checkEmailTitle:'E-Mail prüfen',
  checkEmailMsg:'Wir haben einen Bestätigungslink an deine E-Mail gesendet. Klicke ihn an und melde dich dann an.',
  joinTitle:'Du trittst dem Team bei', joinName:'Dein Name', joinBtn:'Beitreten',
  joinBadCode:'Dieser Einladungslink ist nicht mehr gültig. Frag den Inhaber nach einem neuen.',
  joinDone:'Fertig, du bist beigetreten!',
  inviteHint:'Teile diesen Link mit der neuen Person – sie tritt selbst bei, du musst sie nicht manuell hinzufügen.',
  copyLink:'Link kopieren', linkCopied:'Link kopiert', newInviteCode:'Neuer Code',
  regenConfirm:'Neuen Einladungslink erzeugen? Der alte funktioniert dann nicht mehr.',
  reconnecting:'Verbindung wird wiederhergestellt…',
  unclosedShifts:'Offene Schichten aus der Vergangenheit', unclosedSince:'offen seit'
},

/* ---------------- ENGLISH ---------------- */
en:{ label:'English', locale:'en-GB', cur:'€',
  dows:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  months:['January','February','March','April','May','June','July','August','September','October','November','December'],
  dayNames:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
  tagline:'Shift and attendance tracking', language:'Language',
  owner:'Owner', employee:'Employee', imEmployee:"I'm an employee", imOwner:"I'm the owner",
  email:'Email', password:'Password', signin:'Sign in', signout:'Sign out',
  code:'Employee code', enter:'Enter', demoEnter:'Try the demo',
  demoNote:'Demo mode: data lives in memory only and resets when you reload the page.',
  liveNote:'Connected to the database.',
  badLogin:'Wrong email or password.', badCode:'No such code.',
  tabToday:'Today', tabPlan2:'Plan', tabHist:'History', tabPeople:'People',
  details:'Details',
  atWork:'On shift', hoursToday:'Hours today', costToday:'Cost today',
  atWorkNames:'On shift', nobodyAtWork:'Nobody is on shift',
  arrive:'Clock in', leave:'Clock out', arrived:'In', left:'Out',
  atWorkSince:'On shift since', shiftNotStarted:'Shift has not started yet', doneLbl:'Done',
  breakStart:'Break', breakEnd:'End break', onBreakSince:'On break since',
  breaksLbl:'Breaks', breakTotal:'Breaks total', noBreaks:'No breaks',
  addBreak:'Add a break', netWorked:'Net time', grossTime:'On site',
  recorded:'Recorded', undo:'Undo', fix:'Fix', fixTimes:'Fix the times',
  fixHelp:'If someone forgot to tap, rewrite the time here.', clearDeparture:'Clear clock-out',
  total:'Total', hours:'Hours', cost:'Wage cost', monthTotal:'Month total',
  noRecord:'No record', legendHours:'Numbers on days = hours worked by everyone combined',
  hUnit:'h', minUnit:'min',
  thisWeek:'This week', lastWeek:'Last week', nextWeek:'Next week',
  todayChip:'TODAY', nobody:'nobody', planLbl:'Planned', workedLbl:'Worked',
  tapDay:'Tap a day to edit it', removeShift:'Remove',
  planShift:'Schedule a shift', addShift:'Add a shift', noShifts:'No shifts',
  noShiftsToday:'No shift is scheduled for today.',
  whichShift:'Which shift?', morningS:'Morning', afternoonS:'Afternoon', eveningS:'Evening', otherTime:'Other time',
  person:'Employee', date:'Date', from:'From', to:'To',
  addPerson:'Add an employee', name:'Name', rate:'Hourly rate', noPeople:'You have no employees yet.',
  confirmRemovePerson:'Remove this employee along with their shifts?',
  lastLogin:'Last signed in', neverLoggedIn:'Has not signed in yet', loggedInNow:'Signed in now',
  loginsTitle:'Employee sign-ins', codeLbl:'Code',
  myShifts:'My shifts', myHours:'My hours', gross:'Gross',
  remove:'Remove', cancel:'Cancel', save:'Save',
  saved:'Saved', added:'Added', removed:'Removed',
  nameRequired:'Enter a name.', pickPerson:'Pick an employee.', badTime:'Clock-out must be after clock-in.',
  tooLong:'That shift would be over 16 hours — check the times.',
  plannedTime:'Planned time',
  breakDetail:'Breaks (from – to)',
  changePerson:'Change person',
  whoRecords:'Who records the times',
  modeOwner:'Only me',
  modeSelf:'Employees themselves too',
  modeHint:'With \"Only me\" you tap clock-in and clock-out. With the second option each person records it on their own phone.',
  readOnlyNote:'The owner records the times',
  todayLbl:'Today',
  unplanned:'No plan',
  notScheduled:'Not scheduled today',
  startNow:'Clock in now',
  alreadyOn:'Already on shift',
  planWeek:'Plan the week',
  pickDays:'Which days?',
  noDays:'Pick at least one day.',
  createdN:'Shifts created: ',
  allHaveShift:'Everyone already has a shift',
  badBreak:'The break must fall inside the shift.',
  signUp:'Create account', backToSignin:'Back to sign in',
  noAccountYet:"Don't have an account yet?", haveAccountYet:'Already have an account?',
  confirmPass:'Repeat password', passMismatch:'Passwords do not match.',
  passTooShort:'Password must be at least 6 characters.',
  checkEmailTitle:'Check your email',
  checkEmailMsg:'We sent a confirmation link to your email. Click it, then sign in.',
  joinTitle:"You're joining the team", joinName:'Your name', joinBtn:'Join',
  joinBadCode:'This invite link no longer works. Ask the owner for a new one.',
  joinDone:"Done, you're in!",
  inviteHint:'Share this link with a new person – they join themselves, no need to add them by hand.',
  copyLink:'Copy link', linkCopied:'Link copied', newInviteCode:'New code',
  regenConfirm:'Generate a new invite link? The old one will stop working.',
  reconnecting:'Reconnecting…',
  unclosedShifts:'Unclosed shifts from the past', unclosedSince:'still open since'
},

/* ---------------- HRVATSKI ---------------- */
hr:{ label:'Hrvatski', locale:'hr-HR', cur:'€',
  dows:['Po','Ut','Sr','Če','Pe','Su','Ne'],
  months:['Siječanj','Veljača','Ožujak','Travanj','Svibanj','Lipanj','Srpanj','Kolovoz','Rujan','Listopad','Studeni','Prosinac'],
  dayNames:['Nedjelja','Ponedjeljak','Utorak','Srijeda','Četvrtak','Petak','Subota'],
  tagline:'Evidencija smjena i dolazaka', language:'Jezik',
  owner:'Vlasnik', employee:'Zaposlenik', imEmployee:'Ja sam zaposlenik', imOwner:'Ja sam vlasnik',
  email:'E-mail', password:'Lozinka', signin:'Prijavi se', signout:'Odjava',
  code:'Kod zaposlenika', enter:'Ulaz', demoEnter:'Isprobaj demo',
  demoNote:'Demo način: podaci su samo u memoriji i nakon osvježavanja vraćaju se na početak.',
  liveNote:'Povezano s bazom podataka.',
  badLogin:'Netočan e-mail ili lozinka.', badCode:'Taj kod ne postoji.',
  tabToday:'Danas', tabPlan2:'Raspored', tabHist:'Povijest', tabPeople:'Ljudi',
  details:'Detalji',
  atWork:'Na radu', hoursToday:'Sati danas', costToday:'Trošak danas',
  atWorkNames:'Na radu', nobodyAtWork:'Nitko nije na radu',
  arrive:'Dolazak', leave:'Odlazak', arrived:'Dolazak', left:'Odlazak',
  atWorkSince:'Na radu od', shiftNotStarted:'Smjena još nije počela', doneLbl:'Gotovo',
  breakStart:'Pauza', breakEnd:'Kraj pauze', onBreakSince:'Na pauzi od',
  breaksLbl:'Pauze', breakTotal:'Pauze ukupno', noBreaks:'Nema pauza',
  addBreak:'Dodaj pauzu', netWorked:'Neto vrijeme', grossTime:'Na radnom mjestu',
  recorded:'Zapisano', undo:'Vrati', fix:'Ispravi', fixTimes:'Ispravi vrijeme',
  fixHelp:'Ako se zaboravilo kliknuti, prepiši vrijeme ovdje.', clearDeparture:'Izbriši odlazak',
  total:'Ukupno', hours:'Sati', cost:'Trošak plaća', monthTotal:'Mjesec ukupno',
  noRecord:'Nema zapisa', legendHours:'Brojevi u danima = odrađeni sati svih zajedno',
  hUnit:'h', minUnit:'min',
  thisWeek:'Ovaj tjedan', lastWeek:'Prošli tjedan', nextWeek:'Sljedeći tjedan',
  todayChip:'DANAS', nobody:'nitko', planLbl:'Plan', workedLbl:'Odrađeno',
  tapDay:'Dotakni dan za uređivanje', removeShift:'Ukloni',
  planShift:'Zakaži smjenu', addShift:'Dodaj smjenu', noShifts:'Nema smjena',
  noShiftsToday:'Za danas nema zakazane smjene.',
  whichShift:'Koja smjena?', morningS:'Jutarnja', afternoonS:'Poslijepodnevna', eveningS:'Večernja', otherTime:'Drugo vrijeme',
  person:'Zaposlenik', date:'Datum', from:'Od', to:'Do',
  addPerson:'Dodaj zaposlenika', name:'Ime', rate:'Satnica', noPeople:'Još nemaš zaposlenika.',
  confirmRemovePerson:'Ukloniti ovog zaposlenika zajedno s njegovim smjenama?',
  lastLogin:'Zadnja prijava', neverLoggedIn:'Još se nije prijavio', loggedInNow:'Prijavljen sada',
  loginsTitle:'Prijave zaposlenika', codeLbl:'Kod',
  myShifts:'Moje smjene', myHours:'Moji sati', gross:'Bruto',
  remove:'Ukloni', cancel:'Otkaži', save:'Sačuvaj',
  saved:'Sačuvano', added:'Dodano', removed:'Uklonjeno',
  nameRequired:'Unesi ime.', pickPerson:'Odaberi zaposlenika.', badTime:'Odlazak mora biti nakon dolaska.',
  tooLong:'Smjena bi trajala 16+ sati — provjeri vrijeme.',
  plannedTime:'Planirano vrijeme',
  breakDetail:'Pauze (od – do)',
  changePerson:'Promijeni osobu',
  whoRecords:'Kto upisuje dolaske',
  modeOwner:'Samo ja',
  modeSelf:'I zaposlenici sami',
  modeHint:'Kod „Samo ja“ dolaske i odlaske klikaš ti. Kod druge opcije svatko ih upisuje sam na svom telefonu.',
  readOnlyNote:'Dolaske upisuje vlasnik',
  todayLbl:'Danas',
  unplanned:'Bez plana',
  notScheduled:'Danas nisu u rasporedu',
  startNow:'Dolazak sada',
  alreadyOn:'Već je na radu',
  planWeek:'Planiraj tjedan',
  pickDays:'Koji dani?',
  noDays:'Odaberi barem jedan dan.',
  createdN:'Zakazane smjene: ',
  allHaveShift:'Svi već imaju smjenu',
  badBreak:'Pauza mora biti unutar smjene.',
  signUp:'Napravi račun', backToSignin:'Natrag na prijavu',
  noAccountYet:'Nemaš još račun?', haveAccountYet:'Već imaš račun?',
  confirmPass:'Ponovi lozinku', passMismatch:'Lozinke se ne podudaraju.',
  passTooShort:'Lozinka mora imati najmanje 6 znakova.',
  checkEmailTitle:'Provjeri e-poštu',
  checkEmailMsg:'Poslali smo potvrdni link na tvoju e-poštu. Klikni ga, pa se prijavi.',
  joinTitle:'Pridružuješ se timu', joinName:'Tvoje ime', joinBtn:'Pridruži se',
  joinBadCode:'Ovaj pozivni link više ne vrijedi. Zamoli vlasnika za novi.',
  joinDone:'Gotovo, pridružio/la si se!',
  inviteHint:'Podijeli ovaj link s novom osobom – pridružit će se sama, ne moraš je dodavati ručno.',
  copyLink:'Kopiraj link', linkCopied:'Link kopiran', newInviteCode:'Novi kod',
  regenConfirm:'Generirati novi pozivni link? Stari više neće raditi.',
  reconnecting:'Obnavljam vezu…',
  unclosedShifts:'Nezatvorene smjene iz prošlosti', unclosedSince:'nezatvorena od'
},

/* ---------------- БЪЛГАРСКИ ---------------- */
bg:{ label:'Български', locale:'bg-BG', cur:'€',
  dows:['Пн','Вт','Ср','Чт','Пт','Сб','Нд'],
  months:['Януари','Февруари','Март','Април','Май','Юни','Юли','Август','Септември','Октомври','Ноември','Декември'],
  dayNames:['Неделя','Понеделник','Вторник','Сряда','Четвъртък','Петък','Събота'],
  tagline:'Отчитане на смени и присъствие', language:'Език',
  owner:'Собственик', employee:'Служител', imEmployee:'Аз съм служител', imOwner:'Аз съм собственик',
  email:'Имейл', password:'Парола', signin:'Вход', signout:'Изход',
  code:'Код на служителя', enter:'Влез', demoEnter:'Пробвай демото',
  demoNote:'Демо режим: данните са само в паметта и се връщат в начално състояние при презареждане.',
  liveNote:'Свързано с базата данни.',
  badLogin:'Грешен имейл или парола.', badCode:'Такъв код не съществува.',
  tabToday:'Днес', tabPlan2:'График', tabHist:'История', tabPeople:'Хора',
  details:'Подробности',
  atWork:'На работа', hoursToday:'Часове днес', costToday:'Разход днес',
  atWorkNames:'На работа', nobodyAtWork:'Никой не е на работа',
  arrive:'Идване', leave:'Тръгване', arrived:'Идване', left:'Тръгване',
  atWorkSince:'На работа от', shiftNotStarted:'Смяната още не е започнала', doneLbl:'Готово',
  breakStart:'Почивка', breakEnd:'Край на почивката', onBreakSince:'В почивка от',
  breaksLbl:'Почивки', breakTotal:'Почивки общо', noBreaks:'Няма почивки',
  addBreak:'Добави почивка', netWorked:'Нетно време', grossTime:'На работното място',
  recorded:'Записано', undo:'Върни', fix:'Поправи', fixTimes:'Поправи часа',
  fixHelp:'Ако е забравено да се натисне, пренапиши часа тук.', clearDeparture:'Изтрий тръгването',
  total:'Общо', hours:'Часове', cost:'Разход за заплати', monthTotal:'Месец общо',
  noRecord:'Няма запис', legendHours:'Числата в дните = отработени часове на всички заедно',
  hUnit:'ч', minUnit:'мин',
  thisWeek:'Тази седмица', lastWeek:'Миналата седмица', nextWeek:'Следващата седмица',
  todayChip:'ДНЕС', nobody:'никой', planLbl:'Планирано', workedLbl:'Отработено',
  tapDay:'Докосни ден, за да го редактираш', removeShift:'Премахни',
  planShift:'Планирай смяна', addShift:'Добави смяна', noShifts:'Няма смени',
  noShiftsToday:'За днес няма планирана смяна.',
  whichShift:'Коя смяна?', morningS:'Сутрешна', afternoonS:'Следобедна', eveningS:'Вечерна', otherTime:'Друг час',
  person:'Служител', date:'Дата', from:'От', to:'До',
  addPerson:'Добави служител', name:'Име', rate:'Часова ставка', noPeople:'Още нямаш служители.',
  confirmRemovePerson:'Да премахна ли този служител заедно със смените му?',
  lastLogin:'Последен вход', neverLoggedIn:'Още не е влизал', loggedInNow:'Влязъл сега',
  loginsTitle:'Влизания на служителите', codeLbl:'Код',
  myShifts:'Моите смени', myHours:'Моите часове', gross:'Бруто',
  remove:'Премахни', cancel:'Отказ', save:'Запази',
  saved:'Запазено', added:'Добавено', removed:'Премахнато',
  nameRequired:'Въведи име.', pickPerson:'Избери служител.', badTime:'Тръгването трябва да е след идването.',
  tooLong:'Смяната би била 16+ часа — провери часа.',
  plannedTime:'Планирано време',
  breakDetail:'Почивки (от – до)',
  changePerson:'Смени човека',
  whoRecords:'Кой записва идванията',
  modeOwner:'Само аз',
  modeSelf:'И служителите сами',
  modeHint:'При „Само аз“ идванията и тръгванията отбелязваш ти. При втората опция всеки ги записва сам на своя телефон.',
  readOnlyNote:'Идванията записва собственикът',
  todayLbl:'Днес',
  unplanned:'Без план',
  notScheduled:'Днес не са в графика',
  startNow:'Идване сега',
  alreadyOn:'Вече е на работа',
  planWeek:'Планирай седмицата',
  pickDays:'Кои дни?',
  noDays:'Избери поне един ден.',
  createdN:'Планирани смени: ',
  allHaveShift:'Всички вече имат смяна',
  badBreak:'Почивката трябва да е в рамките на смяната.',
  signUp:'Създай акаунт', backToSignin:'Назад към вход',
  noAccountYet:'Нямаш акаунт?', haveAccountYet:'Вече имаш акаунт?',
  confirmPass:'Паролата отново', passMismatch:'Паролите не съвпадат.',
  passTooShort:'Паролата трябва да е поне 6 символа.',
  checkEmailTitle:'Провери имейла си',
  checkEmailMsg:'Изпратихме потвърждаващ линк на имейла ти. Кликни го и после влез.',
  joinTitle:'Присъединяваш се към екипа', joinName:'Твоето име', joinBtn:'Присъедини се',
  joinBadCode:'Тази покана вече не важи. Помоли собственика за нова.',
  joinDone:'Готово, присъедини се!',
  inviteHint:'Сподели този линк с новия човек – ще се присъедини сам, не е нужно да го добавяш ръчно.',
  copyLink:'Копирай линка', linkCopied:'Линкът е копиран', newInviteCode:'Нов код',
  regenConfirm:'Да генерирам нов линк за покана? Старият ще спре да работи.',
  reconnecting:'Възстановяване на връзката…',
  unclosedShifts:'Незатворени смени от миналото', unclosedSince:'незатворена от'
},

/* ---------------- РУССКИЙ ---------------- */
ru:{ label:'Русский', locale:'ru-RU', cur:'₽',
  dows:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],
  months:['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
  dayNames:['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'],
  tagline:'Учёт смен и посещаемости', language:'Язык',
  owner:'Владелец', employee:'Сотрудник', imEmployee:'Я сотрудник', imOwner:'Я владелец',
  email:'E-mail', password:'Пароль', signin:'Войти', signout:'Выйти',
  code:'Код сотрудника', enter:'Войти', demoEnter:'Попробовать демо',
  demoNote:'Демо-режим: данные хранятся только в памяти и сбрасываются при перезагрузке страницы.',
  liveNote:'Подключено к базе данных.',
  badLogin:'Неверный e-mail или пароль.', badCode:'Такого кода нет.',
  tabToday:'Сегодня', tabPlan2:'График', tabHist:'История', tabPeople:'Люди',
  details:'Подробности',
  atWork:'На смене', hoursToday:'Часов сегодня', costToday:'Расход сегодня',
  atWorkNames:'На смене', nobodyAtWork:'Никого нет на смене',
  arrive:'Приход', leave:'Уход', arrived:'Приход', left:'Уход',
  atWorkSince:'На смене с', shiftNotStarted:'Смена ещё не началась', doneLbl:'Готово',
  breakStart:'Перерыв', breakEnd:'Конец перерыва', onBreakSince:'На перерыве с',
  breaksLbl:'Перерывы', breakTotal:'Перерывы всего', noBreaks:'Перерывов нет',
  addBreak:'Добавить перерыв', netWorked:'Чистое время', grossTime:'На рабочем месте',
  recorded:'Записано', undo:'Отменить', fix:'Исправить', fixTimes:'Исправить время',
  fixHelp:'Если забыли нажать, перепишите время здесь.', clearDeparture:'Удалить уход',
  total:'Всего', hours:'Часы', cost:'Расход на зарплату', monthTotal:'Месяц всего',
  noRecord:'Нет записи', legendHours:'Числа в днях = отработанные часы всех вместе',
  hUnit:'ч', minUnit:'мин',
  thisWeek:'Эта неделя', lastWeek:'Прошлая неделя', nextWeek:'Следующая неделя',
  todayChip:'СЕГОДНЯ', nobody:'никто', planLbl:'План', workedLbl:'Отработано',
  tapDay:'Нажмите на день, чтобы изменить', removeShift:'Убрать',
  planShift:'Запланировать смену', addShift:'Добавить смену', noShifts:'Смен нет',
  noShiftsToday:'На сегодня смен не запланировано.',
  whichShift:'Какая смена?', morningS:'Утренняя', afternoonS:'Дневная', eveningS:'Вечерняя', otherTime:'Другое время',
  person:'Сотрудник', date:'Дата', from:'С', to:'До',
  addPerson:'Добавить сотрудника', name:'Имя', rate:'Ставка в час', noPeople:'У вас пока нет сотрудников.',
  confirmRemovePerson:'Удалить этого сотрудника вместе с его сменами?',
  lastLogin:'Последний вход', neverLoggedIn:'Ещё не входил', loggedInNow:'В сети сейчас',
  loginsTitle:'Входы сотрудников', codeLbl:'Код',
  myShifts:'Мои смены', myHours:'Мои часы', gross:'Брутто',
  remove:'Удалить', cancel:'Отмена', save:'Сохранить',
  saved:'Сохранено', added:'Добавлено', removed:'Удалено',
  nameRequired:'Введите имя.', pickPerson:'Выберите сотрудника.', badTime:'Уход должен быть позже прихода.',
  tooLong:'Смена вышла бы 16+ часов — проверьте время.',
  plannedTime:'Плановое время',
  breakDetail:'Перерывы (с – до)',
  changePerson:'Сменить человека',
  whoRecords:'Кто отмечает время',
  modeOwner:'Только я',
  modeSelf:'И сотрудники сами',
  modeHint:'При «Только я» приход и уход отмечаете вы. При втором варианте каждый отмечает сам на своём телефоне.',
  readOnlyNote:'Время отмечает владелец',
  todayLbl:'Сегодня',
  unplanned:'Без плана',
  notScheduled:'Сегодня не в графике',
  startNow:'Приход сейчас',
  alreadyOn:'Уже на смене',
  planWeek:'Запланировать неделю',
  pickDays:'Какие дни?',
  noDays:'Выберите хотя бы один день.',
  createdN:'Создано смен: ',
  allHaveShift:'У всех уже есть смена',
  badBreak:'Перерыв должен быть внутри смены.',
  signUp:'Создать аккаунт', backToSignin:'Назад ко входу',
  noAccountYet:'Ещё нет аккаунта?', haveAccountYet:'Уже есть аккаунт?',
  confirmPass:'Повторите пароль', passMismatch:'Пароли не совпадают.',
  passTooShort:'Пароль должен быть не менее 6 символов.',
  checkEmailTitle:'Проверьте почту',
  checkEmailMsg:'Мы отправили ссылку для подтверждения на вашу почту. Перейдите по ней, затем войдите.',
  joinTitle:'Вы присоединяетесь к команде', joinName:'Ваше имя', joinBtn:'Присоединиться',
  joinBadCode:'Эта ссылка-приглашение больше не действует. Попросите у владельца новую.',
  joinDone:'Готово, вы присоединились!',
  inviteHint:'Поделитесь этой ссылкой с новым человеком — он присоединится сам, добавлять вручную не нужно.',
  copyLink:'Скопировать ссылку', linkCopied:'Ссылка скопирована', newInviteCode:'Новый код',
  regenConfirm:'Создать новую ссылку-приглашение? Старая перестанет работать.',
  reconnecting:'Восстановление соединения…',
  unclosedShifts:'Незакрытые смены из прошлого', unclosedSince:'не закрыта с'
}

};
