/* ============================================================
   TURNO — preklady
   Ak chceš niečo opraviť, meň len text v úvodzovkách.
   Kľúče vľavo (napr. arrive:) nechaj tak, appka ich hľadá podľa nich.
   'cur' je značka meny — zmeň, ak prevádzka platí v inej.
   ============================================================ */
window.LANGS = {

/* ---------------- SLOVENČINA ---------------- */
sk:{ label:'Slovenčina', locale:'sk-SK', cur:'€',
  dows:['Po','Ut','St','Št','Pi','So','Ne'],
  months:['Január','Február','Marec','Apríl','Máj','Jún','Júl','August','September','Október','November','December'],
  dayNames:['Nedeľa','Pondelok','Utorok','Streda','Štvrtok','Piatok','Sobota'],
  tagline:'Evidencia zmien a dochádzky', language:'Jazyk',
  installApp:'Stiahnuť appku', installHint:'V Chrome/Edge klikni v adresnom riadku na ikonu inštalácie a zvoľ „Nainštalovať“.', installHintIOS:'V Safari ťukni na Zdieľať (□↑) a potom na „Pridať na plochu“.',
  yourPlan:'Tvoj plán', peopleUsageLbl:'zamestnancov', planFreeShort:'Zdarma', planCustomShort:'Individuálne', perMonth:'mesiac', viewPricing:'Cenník', planUpTo:'Do', planCustomRange:'Nad 20 zamestnancov', planOver:'Nad', limitWarn:'Dosiahol si limit svojho plánu.', limitReachedBody:'Na tomto pláne môžeš mať len obmedzený počet zamestnancov. Vyber si vyšší plán nižšie.', pricingTitle:'Cenník', pricingContact:'Platba prebieha bezpečne cez Stripe — kartu ani platobné údaje appka nikdy nevidí.', contactCta:'Napísať nám', upgradeMailSubject:'Chcem upgradnúť Turno plán', upgradeMailBody:'Ahoj, chcem upgradnúť svoj Turno plán na viac zamestnancov.', upgradeBtn:'Vybrať plán', currentPlanLbl:'Aktuálny plán', manageSubBtn:'Spravovať predplatné', checkoutRedirect:'Presmerúvam na platbu…', checkoutSuccessMsg:'Platba prebehla úspešne! Plán sa čoskoro aktualizuje.', checkoutCancelMsg:'Platba bola zrušená.', noSubMsg:'Zatiaľ nemáš platený plán.', checkoutErrMsg:'Platbu sa nepodarilo spustiť. Skús to znova.',
  owner:'Vlastník', employee:'Zamestnanec', imEmployee:'Som zamestnanec', imOwner:'Som vlastník',
  email:'E-mail', password:'Heslo', signin:'Prihlásiť sa', signout:'Odhlásiť',
  code:'Kód zamestnanca', enter:'Vstúpiť', demoEnter:'Vyskúšať demo',
  demoNote:'Demo režim: dáta sú len v pamäti a po obnovení stránky sa vrátia na začiatok.',
  liveNote:'Pripojené na databázu.',
  badLogin:'Nesprávny e-mail alebo heslo.', badCode:'Taký kód neexistuje.',
  tabToday:'Dnes', tabPlan2:'Plán', tabHist:'História', tabNotes:'Poznámky', tabPeople:'Ľudia',
  addNote:'Pridať položku', noteTitle:'Názov', noteDetails:'Podrobnosti', price:'Cena', editNote:'Upraviť položku', noNotes:'Zatiaľ žiadne poznámky. Pridaj napríklad objednávku na zajtra.', costTrend:'Vývoj nákladov na zmeny', last14days:'za posledných 14 dní', supportTitle:'Potrebuješ pomôcť?', supportBody:'Ak niečo nefunguje alebo máš otázku, napíš alebo zavolaj priamo tvorcovi appky.', supportEmail:'Napísať e-mail', lockedEmpBody:'Prístup do aplikácie je pozastavený, lebo predplatné firmy už neplatí. Ozvi sa svojmu zamestnávateľovi — tvoje dáta ostávajú uložené.', payHow:'Ako obnoviť predplatné', payMonthly:'Mesačne', payYearly:'Ročne', yearlyBonus:'Pri ročnej platbe 2 mesiace zadarmo.', payRecipient:'Príjemca', payIban:'IBAN', payAmount:'Suma', payNote:'Poznámka pre príjemcu', copyIban:'Skopírovať IBAN', ibanCopied:'IBAN skopírovaný', payHintMonthly:'Nastav si v banke trvalý príkaz na túto sumu s mesačným opakovaním — sama sa platba neobnoví. Prvú platbu pošli aspoň 3 dni pred koncom predplatného, nech ju stihnem zaevidovať. Do poznámky vždy uveď kód firmy.', payHintYearly:'Pošli jednorazovú platbu aspoň 3 dni pred koncom predplatného. Pred ďalšou obnovou ti to appka pripomenie. Do poznámky vždy uveď kód firmy.', perYear:'rok', subUntil:'Predplatné platí do', subEndsIn:'Predplatné končí o {n} {d} — obnov platbu', dayForms:{one:'deň',few:'dni',many:'dní',other:'dní'}, subEndsToday:'Predplatné končí dnes — obnov platbu', lockedTitle:'Predplatné vypršalo', lockedBody:'Prístup do aplikácie je pozastavený, lebo predplatné už neplatí. Napíš alebo zavolaj a hneď to obnovíme — tvoje dáta ostávajú uložené.',
  details:'Podrobnosti',
  atWork:'V práci', hoursToday:'Hodín dnes', costToday:'Náklad dnes',
  atWorkNames:'V práci', nobodyAtWork:'Nikto nie je v práci',
  arrive:'Príchod', leave:'Odchod', arrived:'Príchod', left:'Odchod',
  atWorkSince:'V práci od', shiftNotStarted:'Zmena ešte nezačala', doneLbl:'Hotovo',
  breakStart:'Prestávka', breakEnd:'Koniec prestávky', onBreakSince:'Na prestávke od',
  breaksLbl:'Prestávky', breakTotal:'Prestávky spolu', noBreaks:'Žiadne prestávky',
  addBreak:'Pridať prestávku', netWorked:'Čistý čas', grossTime:'Na pracovisku',
  recorded:'Zapísané', undo:'Vrátiť', fix:'Opraviť', fixTimes:'Opraviť čas',
  fixHelp:'Ak sa zabudlo kliknúť, prepíš čas tu.', clearDeparture:'Zmazať odchod',
  total:'Spolu', hours:'Hodiny', cost:'Mzdový náklad', monthTotal:'Mesiac celkom',
  noRecord:'Žiadny záznam', legendHours:'Čísla v dňoch = odpracované hodiny všetkých spolu',
  hUnit:'h', minUnit:'min',
  thisWeek:'Tento týždeň', lastWeek:'Minulý týždeň', nextWeek:'Ďalší týždeň',
  todayChip:'DNES', nobody:'nikto', planLbl:'Plán', workedLbl:'Odpracované',
  tapDay:'Ťukni na deň a uprav ho', removeShift:'Odobrať',
  planShift:'Naplánovať zmenu', addShift:'Pridať zmenu', noShifts:'Žiadne zmeny',
  noShiftsToday:'Na dnes nie je naplánovaná žiadna zmena.',
  whichShift:'Ktorá zmena?', morningS:'Ranná', afternoonS:'Poobedná', eveningS:'Večerná', otherTime:'Iný čas',
  person:'Zamestnanec', date:'Dátum', from:'Od', to:'Do',
  addPerson:'Pridať zamestnanca', name:'Meno', rate:'Hodinová mzda', noPeople:'Ešte nemáš žiadnych zamestnancov.',
  confirmRemovePerson:'Odstrániť tohto zamestnanca aj s jeho zmenami?',
  lastLogin:'Naposledy prihlásený', neverLoggedIn:'Zatiaľ sa neprihlásil', loggedInNow:'Prihlásený teraz',
  loginsTitle:'Prihlásenia zamestnancov', codeLbl:'Kód',
  myShifts:'Moje zmeny', myHours:'Moje hodiny', gross:'Brutto',
  remove:'Odstrániť', cancel:'Zrušiť', save:'Uložiť',
  saved:'Uložené', added:'Pridané', removed:'Odstránené',
  nameRequired:'Zadaj meno.', pickPerson:'Vyber zamestnanca.', badTime:'Odchod musí byť po príchode.',
  tooLong:'Zmena by mala 16+ hodín — skontroluj čas.',
  plannedTime:'Plánovaný čas',
  breakDetail:'Prestávky (od – do)',
  changePerson:'Zmeniť človeka',
  whoRecords:'Kto zapisuje príchody',
  modeOwner:'Len ja',
  modeSelf:'Aj zamestnanci sami',
  modeHint:'Pri „Len ja“ klikáš príchody a odchody ty. Pri druhej možnosti si ich zapisuje každý sám vo svojom telefóne.',
  readOnlyNote:'Príchody zapisuje vlastník',
  todayLbl:'Dnes',
  unplanned:'Bez plánu',
  notScheduled:'Dnes nie sú v rozvrhu',
  startNow:'Príchod teraz',
  alreadyOn:'Už je v práci',
  planWeek:'Naplánovať týždeň',
  pickDays:'Ktoré dni?',
  noDays:'Vyber aspoň jeden deň.',
  createdN:'Naplánované zmeny: ',
  allHaveShift:'Všetci už zmenu majú',
  badBreak:'Prestávka musí byť v rámci zmeny.',
  signUp:'Vytvoriť účet', backToSignin:'Späť na prihlásenie',
  noAccountYet:'Nemáš ešte účet?', haveAccountYet:'Už máš účet?',
  confirmPass:'Heslo znova', passMismatch:'Heslá sa nezhodujú.',
  passTooShort:'Heslo musí mať aspoň 6 znakov.',
  checkEmailTitle:'Skontroluj e-mail',
  checkEmailMsg:'Poslali sme potvrdzovací odkaz na tvoj e-mail. Klikni naň a potom sa prihlás.',
  joinTitle:'Pripájaš sa k tímu', joinName:'Tvoje meno', joinBtn:'Pripojiť sa',
  joinBadCode:'Tento pozývací odkaz už neplatí. Popýtaj majiteľa o nový.',
  joinDone:'Hotovo, si pripojený/á!',
  inviteHint:'Zdieľaj tento odkaz s novým človekom – pridá sa sám, nemusíš ho zapisovať ručne.',
  copyLink:'Kopírovať odkaz', linkCopied:'Odkaz skopírovaný', newInviteCode:'Nový kód',
  regenConfirm:'Vygenerovať nový pozývací odkaz? Starý prestane fungovať.',
  reconnecting:'Obnovujem spojenie…',
  unclosedShifts:'Nezavreté zmeny z minulosti', unclosedSince:'nezavretá od'
},

/* ---------------- ČEŠTINA ---------------- */
cs:{ label:'Čeština', locale:'cs-CZ', cur:'Kč',
  dows:['Po','Út','St','Čt','Pá','So','Ne'],
  months:['Leden','Únor','Březen','Duben','Květen','Červen','Červenec','Srpen','Září','Říjen','Listopad','Prosinec'],
  dayNames:['Neděle','Pondělí','Úterý','Středa','Čtvrtek','Pátek','Sobota'],
  tagline:'Evidence směn a příchodů', language:'Jazyk',
  installApp:'Stáhnout appku', installHint:'V Chrome/Edge klikni v adresním řádku na ikonu instalace a zvol „Instalovat“.', installHintIOS:'V Safari ťukni na Sdílet (□↑) a poté na „Přidat na plochu“.',
  yourPlan:'Tvůj plán', peopleUsageLbl:'zaměstnanců', planFreeShort:'Zdarma', planCustomShort:'Individuální', perMonth:'měsíc', viewPricing:'Ceník', planUpTo:'Do', planCustomRange:'Nad 20 zaměstnanců', planOver:'Nad', limitWarn:'Dosáhl jsi limitu svého plánu.', limitReachedBody:'Na tomto plánu můžeš mít jen omezený počet zaměstnanců. Vyber si vyšší plán níže.', pricingTitle:'Ceník', pricingContact:'Platba probíhá bezpečně přes Stripe — kartu ani platební údaje appka nikdy nevidí.', contactCta:'Napsat nám', upgradeMailSubject:'Chci upgradovat Turno plán', upgradeMailBody:'Ahoj, chci upgradovat svůj Turno plán na více zaměstnanců.', upgradeBtn:'Vybrat plán', currentPlanLbl:'Aktuální plán', manageSubBtn:'Spravovat předplatné', checkoutRedirect:'Přesměrovávám na platbu…', checkoutSuccessMsg:'Platba proběhla úspěšně! Plán se brzy aktualizuje.', checkoutCancelMsg:'Platba byla zrušena.', noSubMsg:'Zatím nemáš placený plán.', checkoutErrMsg:'Platbu se nepodařilo spustit. Zkus to znovu.',
  owner:'Vlastník', employee:'Zaměstnanec', imEmployee:'Jsem zaměstnanec', imOwner:'Jsem vlastník',
  email:'E-mail', password:'Heslo', signin:'Přihlásit se', signout:'Odhlásit',
  code:'Kód zaměstnance', enter:'Vstoupit', demoEnter:'Vyzkoušet demo',
  demoNote:'Demo režim: data jsou jen v paměti a po obnovení stránky se vrátí na začátek.',
  liveNote:'Připojeno k databázi.',
  badLogin:'Nesprávný e-mail nebo heslo.', badCode:'Takový kód neexistuje.',
  tabToday:'Dnes', tabPlan2:'Plán', tabHist:'Historie', tabNotes:'Poznámky', tabPeople:'Lidé',
  addNote:'Přidat položku', noteTitle:'Název', noteDetails:'Podrobnosti', price:'Cena', editNote:'Upravit položku', noNotes:'Zatím žádné poznámky. Přidej například objednávku na zítra.', costTrend:'Vývoj nákladů na směny', last14days:'za posledních 14 dní', supportTitle:'Potřebuješ pomoct?', supportBody:'Pokud něco nefunguje nebo máš dotaz, napiš nebo zavolej přímo tvůrci appky.', supportEmail:'Napsat e-mail', lockedEmpBody:'Přístup do aplikace je pozastavený, protože předplatné firmy už neplatí. Ozvi se svému zaměstnavateli — tvoje data zůstávají uložená.', payHow:'Jak obnovit předplatné', payMonthly:'Měsíčně', payYearly:'Ročně', yearlyBonus:'Při roční platbě 2 měsíce zdarma.', payRecipient:'Příjemce', payIban:'IBAN', payAmount:'Částka', payNote:'Zpráva pro příjemce', copyIban:'Zkopírovat IBAN', ibanCopied:'IBAN zkopírován', payHintMonthly:'Nastav si v bance trvalý příkaz na tuto částku s měsíčním opakováním — sama se platba neobnoví. První platbu pošli aspoň 3 dny před koncem předplatného, ať ji stihnu zaevidovat. Do zprávy vždy uveď kód firmy.', payHintYearly:'Pošli jednorázovou platbu aspoň 3 dny před koncem předplatného. Před další obnovou ti to appka připomene. Do zprávy vždy uveď kód firmy.', perYear:'rok', subUntil:'Předplatné platí do', subEndsIn:'Předplatné končí za {n} {d} — obnov platbu', dayForms:{one:'den',few:'dny',many:'dní',other:'dní'}, subEndsToday:'Předplatné končí dnes — obnov platbu', lockedTitle:'Předplatné vypršelo', lockedBody:'Přístup do aplikace je pozastavený, protože předplatné už neplatí. Napiš nebo zavolej a hned to obnovíme — tvoje data zůstávají uložená.',
  details:'Podrobnosti',
  atWork:'V práci', hoursToday:'Hodin dnes', costToday:'Náklad dnes',
  atWorkNames:'V práci', nobodyAtWork:'Nikdo není v práci',
  arrive:'Příchod', leave:'Odchod', arrived:'Příchod', left:'Odchod',
  atWorkSince:'V práci od', shiftNotStarted:'Směna ještě nezačala', doneLbl:'Hotovo',
  breakStart:'Pauza', breakEnd:'Konec pauzy', onBreakSince:'Na pauze od',
  breaksLbl:'Pauzy', breakTotal:'Pauzy celkem', noBreaks:'Žádné pauzy',
  addBreak:'Přidat pauzu', netWorked:'Čistý čas', grossTime:'Na pracovišti',
  recorded:'Zapsáno', undo:'Vrátit', fix:'Opravit', fixTimes:'Opravit čas',
  fixHelp:'Pokud se zapomnělo kliknout, přepiš čas tady.', clearDeparture:'Smazat odchod',
  total:'Celkem', hours:'Hodiny', cost:'Mzdový náklad', monthTotal:'Měsíc celkem',
  noRecord:'Žádný záznam', legendHours:'Čísla ve dnech = odpracované hodiny všech dohromady',
  hUnit:'h', minUnit:'min',
  thisWeek:'Tento týden', lastWeek:'Minulý týden', nextWeek:'Další týden',
  todayChip:'DNES', nobody:'nikdo', planLbl:'Plán', workedLbl:'Odpracováno',
  tapDay:'Klepni na den a uprav ho', removeShift:'Odebrat',
  planShift:'Naplánovat směnu', addShift:'Přidat směnu', noShifts:'Žádné směny',
  noShiftsToday:'Na dnes není naplánovaná žádná směna.',
  whichShift:'Která směna?', morningS:'Ranní', afternoonS:'Odpolední', eveningS:'Večerní', otherTime:'Jiný čas',
  person:'Zaměstnanec', date:'Datum', from:'Od', to:'Do',
  addPerson:'Přidat zaměstnance', name:'Jméno', rate:'Hodinová mzda', noPeople:'Ještě nemáš žádné zaměstnance.',
  confirmRemovePerson:'Odstranit tohoto zaměstnance i s jeho směnami?',
  lastLogin:'Naposledy přihlášen', neverLoggedIn:'Zatím se nepřihlásil', loggedInNow:'Přihlášen nyní',
  loginsTitle:'Přihlášení zaměstnanců', codeLbl:'Kód',
  myShifts:'Moje směny', myHours:'Moje hodiny', gross:'Brutto',
  remove:'Odstranit', cancel:'Zrušit', save:'Uložit',
  saved:'Uloženo', added:'Přidáno', removed:'Odstraněno',
  nameRequired:'Zadej jméno.', pickPerson:'Vyber zaměstnance.', badTime:'Odchod musí být po příchodu.',
  tooLong:'Směna by měla 16+ hodin — zkontroluj čas.',
  plannedTime:'Plánovaný čas',
  breakDetail:'Pauzy (od – do)',
  changePerson:'Změnit člověka',
  whoRecords:'Kdo zapisuje příchody',
  modeOwner:'Jen já',
  modeSelf:'I zaměstnanci sami',
  modeHint:'U „Jen já“ klikáš příchody a odchody ty. U druhé možnosti si je zapisuje každý sám ve svém telefonu.',
  readOnlyNote:'Příchody zapisuje vlastník',
  todayLbl:'Dnes',
  unplanned:'Bez plánu',
  notScheduled:'Dnes nejsou v rozvrhu',
  startNow:'Příchod teď',
  alreadyOn:'Už je v práci',
  planWeek:'Naplánovat týden',
  pickDays:'Které dny?',
  noDays:'Vyber aspoň jeden den.',
  createdN:'Naplánované směny: ',
  allHaveShift:'Všichni už směnu mají',
  badBreak:'Pauza musí být v rámci směny.',
  signUp:'Vytvořit účet', backToSignin:'Zpět na přihlášení',
  noAccountYet:'Ještě nemáš účet?', haveAccountYet:'Už máš účet?',
  confirmPass:'Heslo znovu', passMismatch:'Hesla se neshodují.',
  passTooShort:'Heslo musí mít alespoň 6 znaků.',
  checkEmailTitle:'Zkontroluj e-mail',
  checkEmailMsg:'Poslali jsme potvrzovací odkaz na tvůj e-mail. Klikni na něj a pak se přihlas.',
  joinTitle:'Připojuješ se k týmu', joinName:'Tvoje jméno', joinBtn:'Připojit se',
  joinBadCode:'Tento zvací odkaz už neplatí. Popros majitele o nový.',
  joinDone:'Hotovo, jsi připojen/a!',
  inviteHint:'Sdílej tento odkaz s novým člověkem – přidá se sám, nemusíš ho zapisovat ručně.',
  copyLink:'Kopírovat odkaz', linkCopied:'Odkaz zkopírován', newInviteCode:'Nový kód',
  regenConfirm:'Vygenerovat nový zvací odkaz? Starý přestane fungovat.',
  reconnecting:'Obnovuji spojení…',
  unclosedShifts:'Nezavřené směny z minulosti', unclosedSince:'nezavřená od'
},

/* ---------------- POLSKI ---------------- */
pl:{ label:'Polski', locale:'pl-PL', cur:'zł',
  dows:['Pn','Wt','Śr','Cz','Pt','So','Nd'],
  months:['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'],
  dayNames:['Niedziela','Poniedziałek','Wtorek','Środa','Czwartek','Piątek','Sobota'],
  tagline:'Ewidencja zmian i obecności', language:'Język',
  installApp:'Pobierz aplikację', installHint:'W Chrome/Edge kliknij ikonę instalacji w pasku adresu i wybierz „Zainstaluj”.', installHintIOS:'W Safari stuknij Udostępnij (□↑), a potem „Dodaj do ekranu głównego”.',
  yourPlan:'Twój plan', peopleUsageLbl:'pracowników', planFreeShort:'Za darmo', planCustomShort:'Indywidualnie', perMonth:'miesiąc', viewPricing:'Cennik', planUpTo:'Do', planCustomRange:'Powyżej 20 pracowników', planOver:'Powyżej', limitWarn:'Osiągnąłeś limit swojego planu.', limitReachedBody:'Na tym planie możesz mieć ograniczoną liczbę pracowników. Wybierz wyższy plan poniżej.', pricingTitle:'Cennik', pricingContact:'Płatność odbywa się bezpiecznie przez Stripe — aplikacja nigdy nie widzi danych karty.', contactCta:'Napisz do nas', upgradeMailSubject:'Chcę uaktualnić plan Turno', upgradeMailBody:'Cześć, chcę uaktualnić mój plan Turno na więcej pracowników.', upgradeBtn:'Wybierz plan', currentPlanLbl:'Aktualny plan', manageSubBtn:'Zarządzaj subskrypcją', checkoutRedirect:'Przekierowuję do płatności…', checkoutSuccessMsg:'Płatność zakończona sukcesem! Plan wkrótce się zaktualizuje.', checkoutCancelMsg:'Płatność została anulowana.', noSubMsg:'Nie masz jeszcze płatnego planu.', checkoutErrMsg:'Nie udało się rozpocząć płatności. Spróbuj ponownie.',
  owner:'Właściciel', employee:'Pracownik', imEmployee:'Jestem pracownikiem', imOwner:'Jestem właścicielem',
  email:'E-mail', password:'Hasło', signin:'Zaloguj się', signout:'Wyloguj',
  code:'Kod pracownika', enter:'Wejdź', demoEnter:'Wypróbuj demo',
  demoNote:'Tryb demo: dane są tylko w pamięci i po odświeżeniu strony wracają do początku.',
  liveNote:'Połączono z bazą danych.',
  badLogin:'Nieprawidłowy e-mail lub hasło.', badCode:'Taki kod nie istnieje.',
  tabToday:'Dziś', tabPlan2:'Plan', tabHist:'Historia', tabNotes:'Notatki', tabPeople:'Ludzie',
  addNote:'Dodaj pozycję', noteTitle:'Nazwa', noteDetails:'Szczegóły', price:'Cena', editNote:'Edytuj pozycję', noNotes:'Brak notatek. Dodaj np. zamówienie na jutro.', costTrend:'Trend kosztów zmian', last14days:'za ostatnie 14 dni', supportTitle:'Potrzebujesz pomocy?', supportBody:'Jeśli coś nie działa lub masz pytanie, napisz lub zadzwoń bezpośrednio do twórcy aplikacji.', supportEmail:'Napisz e-mail', lockedEmpBody:'Dostęp do aplikacji jest wstrzymany, ponieważ subskrypcja firmy wygasła. Skontaktuj się z pracodawcą — Twoje dane pozostają zapisane.', payHow:'Jak odnowić subskrypcję', payMonthly:'Miesięcznie', payYearly:'Rocznie', yearlyBonus:'Przy płatności rocznej 2 miesiące gratis.', payRecipient:'Odbiorca', payIban:'IBAN', payAmount:'Kwota', payNote:'Tytuł przelewu', copyIban:'Kopiuj IBAN', ibanCopied:'IBAN skopiowany', payHintMonthly:'Ustaw w banku zlecenie stałe na tę kwotę z powtarzaniem co miesiąc — płatność sama się nie odnowi. Pierwszy przelew wyślij co najmniej 3 dni przed końcem subskrypcji, żebym zdążył go zaksięgować. W tytule zawsze podaj kod firmy.', payHintYearly:'Wyślij jednorazowy przelew co najmniej 3 dni przed końcem subskrypcji. Przed kolejnym odnowieniem aplikacja Ci przypomni. W tytule zawsze podaj kod firmy.', perYear:'rok', subUntil:'Subskrypcja ważna do', subEndsIn:'Subskrypcja kończy się za {n} {d} — odnów płatność', dayForms:{one:'dzień',few:'dni',many:'dni',other:'dni'}, subEndsToday:'Subskrypcja kończy się dziś — odnów płatność', lockedTitle:'Subskrypcja wygasła', lockedBody:'Dostęp do aplikacji jest wstrzymany, ponieważ subskrypcja wygasła. Napisz lub zadzwoń, a od razu ją odnowimy — Twoje dane pozostają zapisane.',
  details:'Szczegóły',
  atWork:'W pracy', hoursToday:'Godzin dziś', costToday:'Koszt dziś',
  atWorkNames:'W pracy', nobodyAtWork:'Nikogo nie ma w pracy',
  arrive:'Wejście', leave:'Wyjście', arrived:'Wejście', left:'Wyjście',
  atWorkSince:'W pracy od', shiftNotStarted:'Zmiana jeszcze nie zaczęła się', doneLbl:'Gotowe',
  breakStart:'Przerwa', breakEnd:'Koniec przerwy', onBreakSince:'Na przerwie od',
  breaksLbl:'Przerwy', breakTotal:'Przerwy razem', noBreaks:'Brak przerw',
  addBreak:'Dodaj przerwę', netWorked:'Czas netto', grossTime:'W pracy łącznie',
  recorded:'Zapisano', undo:'Cofnij', fix:'Popraw', fixTimes:'Popraw czas',
  fixHelp:'Jeśli zapomniano kliknąć, popraw czas tutaj.', clearDeparture:'Usuń wyjście',
  total:'Razem', hours:'Godziny', cost:'Koszt wynagrodzeń', monthTotal:'Miesiąc razem',
  noRecord:'Brak zapisu', legendHours:'Liczby w dniach = przepracowane godziny wszystkich razem',
  hUnit:'godz.', minUnit:'min',
  thisWeek:'Ten tydzień', lastWeek:'Poprzedni tydzień', nextWeek:'Następny tydzień',
  todayChip:'DZIŚ', nobody:'nikt', planLbl:'Plan', workedLbl:'Przepracowano',
  tapDay:'Dotknij dzień, aby go zmienić', removeShift:'Usuń',
  planShift:'Zaplanuj zmianę', addShift:'Dodaj zmianę', noShifts:'Brak zmian',
  noShiftsToday:'Na dziś nie zaplanowano żadnej zmiany.',
  whichShift:'Która zmiana?', morningS:'Ranna', afternoonS:'Popołudniowa', eveningS:'Wieczorna', otherTime:'Inna godzina',
  person:'Pracownik', date:'Data', from:'Od', to:'Do',
  addPerson:'Dodaj pracownika', name:'Imię', rate:'Stawka godzinowa', noPeople:'Nie masz jeszcze pracowników.',
  confirmRemovePerson:'Usunąć tego pracownika razem z jego zmianami?',
  lastLogin:'Ostatnie logowanie', neverLoggedIn:'Jeszcze się nie logował', loggedInNow:'Zalogowany teraz',
  loginsTitle:'Logowania pracowników', codeLbl:'Kod',
  myShifts:'Moje zmiany', myHours:'Moje godziny', gross:'Brutto',
  remove:'Usuń', cancel:'Anuluj', save:'Zapisz',
  saved:'Zapisano', added:'Dodano', removed:'Usunięto',
  nameRequired:'Podaj imię.', pickPerson:'Wybierz pracownika.', badTime:'Wyjście musi być po wejściu.',
  tooLong:'Zmiana miałaby 16+ godzin — sprawdź godziny.',
  plannedTime:'Planowana godzina',
  breakDetail:'Przerwy (od – do)',
  changePerson:'Zmień osobę',
  whoRecords:'Kto zapisuje wejścia',
  modeOwner:'Tylko ja',
  modeSelf:'Także pracownicy sami',
  modeHint:'Przy „Tylko ja” wejścia i wyjścia klikasz Ty. Przy drugiej opcji każdy zapisuje je sam w swoim telefonie.',
  readOnlyNote:'Wejścia zapisuje właściciel',
  todayLbl:'Dziś',
  unplanned:'Bez planu',
  notScheduled:'Dziś nie ma ich w grafiku',
  startNow:'Wejście teraz',
  alreadyOn:'Już jest w pracy',
  planWeek:'Zaplanuj tydzień',
  pickDays:'Które dni?',
  noDays:'Wybierz co najmniej jeden dzień.',
  createdN:'Zaplanowane zmiany: ',
  allHaveShift:'Wszyscy już mają zmianę',
  badBreak:'Przerwa musi mieścić się w zmianie.',
  signUp:'Utwórz konto', backToSignin:'Powrót do logowania',
  noAccountYet:'Nie masz jeszcze konta?', haveAccountYet:'Masz już konto?',
  confirmPass:'Powtórz hasło', passMismatch:'Hasła się nie zgadzają.',
  passTooShort:'Hasło musi mieć co najmniej 6 znaków.',
  checkEmailTitle:'Sprawdź e-mail',
  checkEmailMsg:'Wysłaliśmy link potwierdzający na Twój e-mail. Kliknij go, a potem się zaloguj.',
  joinTitle:'Dołączasz do zespołu', joinName:'Twoje imię', joinBtn:'Dołącz',
  joinBadCode:'Ten link zaproszenia już nie działa. Poproś właściciela o nowy.',
  joinDone:'Gotowe, jesteś dołączony/a!',
  inviteHint:'Udostępnij ten link nowej osobie – dołączy się sama, nie musisz jej dodawać ręcznie.',
  copyLink:'Kopiuj link', linkCopied:'Link skopiowany', newInviteCode:'Nowy kod',
  regenConfirm:'Wygenerować nowy link zaproszenia? Stary przestanie działać.',
  reconnecting:'Wznawiam połączenie…',
  unclosedShifts:'Niezamknięte zmiany z przeszłości', unclosedSince:'niezamknięta od'
},

/* ---------------- MAGYAR ---------------- */
hu:{ label:'Magyar', locale:'hu-HU', cur:'Ft',
  dows:['H','K','Sze','Cs','P','Szo','V'],
  months:['Január','Február','Március','Április','Május','Június','Július','Augusztus','Szeptember','Október','November','December'],
  dayNames:['Vasárnap','Hétfő','Kedd','Szerda','Csütörtök','Péntek','Szombat'],
  tagline:'Beosztás és jelenlét nyilvántartás', language:'Nyelv',
  installApp:'Alkalmazás letöltése', installHint:'Chrome/Edge-ben kattints a címsorban a telepítés ikonra, majd válaszd a „Telepítés” lehetőséget.', installHintIOS:'Safariban koppints a Megosztás (□↑) gombra, majd az „Hozzáadás a kezdőképernyőhöz” opcióra.',
  yourPlan:'Csomagod', peopleUsageLbl:'alkalmazott', planFreeShort:'Ingyenes', planCustomShort:'Egyedi', perMonth:'hónap', viewPricing:'Árlista', planUpTo:'Legfeljebb', planCustomRange:'20 alkalmazott felett', planOver:'Felett', limitWarn:'Elérted a csomagod limitjét.', limitReachedBody:'Ezen a csomagon csak korlátozott számú alkalmazottad lehet. Válassz magasabb csomagot lent.', pricingTitle:'Árlista', pricingContact:'A fizetés biztonságosan a Stripe-on keresztül történik — az app sosem látja a kártyaadataidat.', contactCta:'Írj nekünk', upgradeMailSubject:'Turno csomag frissítése', upgradeMailBody:'Szia, szeretném frissíteni a Turno csomagomat, hogy több alkalmazottam lehessen.', upgradeBtn:'Csomag kiválasztása', currentPlanLbl:'Jelenlegi csomag', manageSubBtn:'Előfizetés kezelése', checkoutRedirect:'Átirányítás a fizetéshez…', checkoutSuccessMsg:'A fizetés sikeres volt! A csomag hamarosan frissül.', checkoutCancelMsg:'A fizetés megszakadt.', noSubMsg:'Még nincs fizetős csomagod.', checkoutErrMsg:'Nem sikerült elindítani a fizetést. Próbáld újra.',
  owner:'Tulajdonos', employee:'Munkatárs', imEmployee:'Munkatárs vagyok', imOwner:'Tulajdonos vagyok',
  email:'E-mail', password:'Jelszó', signin:'Bejelentkezés', signout:'Kilépés',
  code:'Munkatárs kódja', enter:'Belépés', demoEnter:'Demó kipróbálása',
  demoNote:'Demó mód: az adatok csak a memóriában vannak, az oldal újratöltésekor visszaállnak.',
  liveNote:'Kapcsolódva az adatbázishoz.',
  badLogin:'Hibás e-mail vagy jelszó.', badCode:'Ilyen kód nem létezik.',
  tabToday:'Ma', tabPlan2:'Beosztás', tabHist:'Előzmények', tabNotes:'Jegyzetek', tabPeople:'Emberek',
  addNote:'Tétel hozzáadása', noteTitle:'Megnevezés', noteDetails:'Részletek', price:'Ár', editNote:'Tétel szerkesztése', noNotes:'Még nincs egyetlen jegyzet sem. Adj hozzá például egy holnapi rendelést.', costTrend:'Műszakköltségek alakulása', last14days:'az elmúlt 14 napban', supportTitle:'Segítségre van szükséged?', supportBody:'Ha valami nem működik, vagy kérdésed van, írj vagy hívd közvetlenül az alkalmazás készítőjét.', supportEmail:'E-mail írása', lockedEmpBody:'Az alkalmazáshoz való hozzáférés szünetel, mert a cég előfizetése lejárt. Fordulj a munkáltatódhoz — az adataid megmaradnak.', payHow:'Hogyan újítsd meg az előfizetést', payMonthly:'Havonta', payYearly:'Évente', yearlyBonus:'Éves fizetésnél 2 hónap ingyenes.', payRecipient:'Kedvezményezett', payIban:'IBAN', payAmount:'Összeg', payNote:'Közlemény', copyIban:'IBAN másolása', ibanCopied:'IBAN másolva', payHintMonthly:'Állíts be a bankodban állandó átutalást erre az összegre, havi ismétléssel — a fizetés magától nem újul meg. Az első utalást legalább 3 nappal az előfizetés vége előtt küldd el, hogy rögzíteni tudjam. A közleménybe mindig írd be a cég kódját.', payHintYearly:'Küldj egyszeri utalást legalább 3 nappal az előfizetés vége előtt. A következő megújítás előtt az alkalmazás emlékeztetni fog. A közleménybe mindig írd be a cég kódját.', perYear:'év', subUntil:'Az előfizetés érvényes eddig', subEndsIn:'Az előfizetés {n} {d} múlva lejár — újítsd meg', dayForms:{one:'nap',other:'nap'}, subEndsToday:'Az előfizetés ma lejár — újítsd meg', lockedTitle:'Az előfizetés lejárt', lockedBody:'Az alkalmazáshoz való hozzáférés szünetel, mert az előfizetés lejárt. Írj vagy hívj minket, és azonnal megújítjuk — az adataid megmaradnak.',
  details:'Részletek',
  atWork:'Munkában', hoursToday:'Mai órák', costToday:'Mai költség',
  atWorkNames:'Munkában', nobodyAtWork:'Senki nincs munkában',
  arrive:'Érkezés', leave:'Elmenés', arrived:'Érkezés', left:'Elmenés',
  atWorkSince:'Munkában ettől', shiftNotStarted:'A műszak még nem kezdődött el', doneLbl:'Kész',
  breakStart:'Szünet', breakEnd:'Szünet vége', onBreakSince:'Szüneten ettől',
  breaksLbl:'Szünetek', breakTotal:'Szünetek összesen', noBreaks:'Nincs szünet',
  addBreak:'Szünet hozzáadása', netWorked:'Nettó idő', grossTime:'Munkahelyen töltött',
  recorded:'Rögzítve', undo:'Visszavonás', fix:'Javítás', fixTimes:'Idő javítása',
  fixHelp:'Ha elmaradt a kattintás, itt írd át az időt.', clearDeparture:'Elmenés törlése',
  total:'Összesen', hours:'Órák', cost:'Bérköltség', monthTotal:'Hónap összesen',
  noRecord:'Nincs bejegyzés', legendHours:'A napokban lévő számok = mindenki ledolgozott órái',
  hUnit:'ó', minUnit:'p',
  thisWeek:'Ez a hét', lastWeek:'Előző hét', nextWeek:'Következő hét',
  todayChip:'MA', nobody:'senki', planLbl:'Terv', workedLbl:'Ledolgozva',
  tapDay:'Koppints egy napra a szerkesztéshez', removeShift:'Eltávolítás',
  planShift:'Műszak beosztása', addShift:'Műszak hozzáadása', noShifts:'Nincs műszak',
  noShiftsToday:'Ma nincs beosztott műszak.',
  whichShift:'Melyik műszak?', morningS:'Reggeli', afternoonS:'Délutáni', eveningS:'Esti', otherTime:'Más időpont',
  person:'Munkatárs', date:'Dátum', from:'Ettől', to:'Eddig',
  addPerson:'Munkatárs hozzáadása', name:'Név', rate:'Órabér', noPeople:'Még nincs egy munkatársad sem.',
  confirmRemovePerson:'Törlöd ezt a munkatársat a műszakjaival együtt?',
  lastLogin:'Utolsó belépés', neverLoggedIn:'Még nem lépett be', loggedInNow:'Most bejelentkezve',
  loginsTitle:'Munkatársak belépései', codeLbl:'Kód',
  myShifts:'Műszakjaim', myHours:'Óráim', gross:'Bruttó',
  remove:'Törlés', cancel:'Mégse', save:'Mentés',
  saved:'Mentve', added:'Hozzáadva', removed:'Törölve',
  nameRequired:'Add meg a nevet.', pickPerson:'Válassz munkatársat.', badTime:'Az elmenés az érkezés után legyen.',
  tooLong:'A műszak 16+ óra lenne — ellenőrizd az időt.',
  plannedTime:'Tervezett idő',
  breakDetail:'Szünetek (-tól -ig)',
  changePerson:'Személy módosítása',
  whoRecords:'Ki rögzíti az érkezéseket',
  modeOwner:'Csak én',
  modeSelf:'A munkatársak is maguk',
  modeHint:'A „Csak én” esetén te rögzíted az érkezést és elmenést. A másik lehetőségnél mindenki maga rögzíti a saját telefonján.',
  readOnlyNote:'Az érkezéseket a tulajdonos rögzíti',
  todayLbl:'Ma',
  unplanned:'Terv nélkül',
  notScheduled:'Ma nincsenek beosztva',
  startNow:'Érkezés most',
  alreadyOn:'Már munkában van',
  planWeek:'Hét beosztása',
  pickDays:'Mely napok?',
  noDays:'Válassz legalább egy napot.',
  createdN:'Beosztott műszakok: ',
  allHaveShift:'Mindenkinek van már műszakja',
  badBreak:'A szünetnek a műszakon belül kell lennie.',
  signUp:'Fiók létrehozása', backToSignin:'Vissza a bejelentkezéshez',
  noAccountYet:'Még nincs fiókod?', haveAccountYet:'Már van fiókod?',
  confirmPass:'Jelszó újra', passMismatch:'A jelszavak nem egyeznek.',
  passTooShort:'A jelszónak legalább 6 karakternek kell lennie.',
  checkEmailTitle:'Nézd meg az e-mailed',
  checkEmailMsg:'Küldtünk egy megerősítő linket az e-mail címedre. Kattints rá, majd jelentkezz be.',
  joinTitle:'Csatlakozol a csapathoz', joinName:'A neved', joinBtn:'Csatlakozás',
  joinBadCode:'Ez a meghívó link már nem érvényes. Kérj újat a tulajdonostól.',
  joinDone:'Kész, csatlakoztál!',
  inviteHint:'Oszd meg ezt a linket az új emberrel – magától csatlakozik, nem kell kézzel hozzáadnod.',
  copyLink:'Link másolása', linkCopied:'Link másolva', newInviteCode:'Új kód',
  regenConfirm:'Új meghívó linket generálunk? A régi megszűnik működni.',
  reconnecting:'Kapcsolat helyreállítása…',
  unclosedShifts:'Lezáratlan műszakok a múltból', unclosedSince:'lezáratlan ekkortól:'
},

/* ---------------- DEUTSCH ---------------- */
de:{ label:'Deutsch', locale:'de-DE', cur:'€',
  dows:['Mo','Di','Mi','Do','Fr','Sa','So'],
  months:['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
  dayNames:['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
  tagline:'Schicht- und Anwesenheitserfassung', language:'Sprache',
  installApp:'App herunterladen', installHint:'Klicke in Chrome/Edge in der Adressleiste auf das Installationssymbol und wähle „Installieren“.', installHintIOS:'Tippe in Safari auf Teilen (□↑) und dann auf „Zum Home-Bildschirm“.',
  yourPlan:'Dein Plan', peopleUsageLbl:'Mitarbeiter', planFreeShort:'Kostenlos', planCustomShort:'Individuell', perMonth:'Monat', viewPricing:'Preise', planUpTo:'Bis zu', planCustomRange:'Über 20 Mitarbeiter', planOver:'Über', limitWarn:'Du hast das Limit deines Plans erreicht.', limitReachedBody:'In diesem Plan kannst du nur eine begrenzte Anzahl an Mitarbeitern haben. Wähle unten einen höheren Plan.', pricingTitle:'Preise', pricingContact:'Die Zahlung läuft sicher über Stripe — die App sieht deine Kartendaten nie.', contactCta:'Schreib uns', upgradeMailSubject:'Turno-Plan upgraden', upgradeMailBody:'Hallo, ich möchte meinen Turno-Plan upgraden, um mehr Mitarbeiter hinzuzufügen.', upgradeBtn:'Plan wählen', currentPlanLbl:'Aktueller Plan', manageSubBtn:'Abo verwalten', checkoutRedirect:'Weiterleitung zur Zahlung…', checkoutSuccessMsg:'Zahlung erfolgreich! Der Plan wird in Kürze aktualisiert.', checkoutCancelMsg:'Zahlung wurde abgebrochen.', noSubMsg:'Du hast noch keinen bezahlten Plan.', checkoutErrMsg:'Zahlung konnte nicht gestartet werden. Versuch es erneut.',
  owner:'Inhaber', employee:'Mitarbeiter', imEmployee:'Ich bin Mitarbeiter', imOwner:'Ich bin Inhaber',
  email:'E-Mail', password:'Passwort', signin:'Anmelden', signout:'Abmelden',
  code:'Mitarbeiter-Code', enter:'Weiter', demoEnter:'Demo testen',
  demoNote:'Demo-Modus: Daten liegen nur im Speicher und werden beim Neuladen zurückgesetzt.',
  liveNote:'Mit Datenbank verbunden.',
  badLogin:'E-Mail oder Passwort falsch.', badCode:'Diesen Code gibt es nicht.',
  tabToday:'Heute', tabPlan2:'Plan', tabHist:'Verlauf', tabNotes:'Notizen', tabPeople:'Leute',
  addNote:'Eintrag hinzufügen', noteTitle:'Name', noteDetails:'Details', price:'Preis', editNote:'Eintrag bearbeiten', noNotes:'Noch keine Notizen. Füge z. B. eine Bestellung für morgen hinzu.', costTrend:'Entwicklung der Schichtkosten', last14days:'der letzten 14 Tage', supportTitle:'Brauchst du Hilfe?', supportBody:'Wenn etwas nicht funktioniert oder du eine Frage hast, schreib oder ruf direkt den Entwickler der App an.', supportEmail:'E-Mail schreiben', lockedEmpBody:'Der Zugang zur App ist pausiert, weil das Abo der Firma abgelaufen ist. Wende dich an deinen Arbeitgeber — deine Daten bleiben gespeichert.', payHow:'Abo verlängern', payMonthly:'Monatlich', payYearly:'Jährlich', yearlyBonus:'Bei jährlicher Zahlung 2 Monate gratis.', payRecipient:'Empfänger', payIban:'IBAN', payAmount:'Betrag', payNote:'Verwendungszweck', copyIban:'IBAN kopieren', ibanCopied:'IBAN kopiert', payHintMonthly:'Richte bei deiner Bank einen Dauerauftrag über diesen Betrag mit monatlicher Wiederholung ein — von selbst verlängert sich die Zahlung nicht. Die erste Überweisung mindestens 3 Tage vor Ablauf senden, damit ich sie erfassen kann. Gib im Verwendungszweck immer den Firmencode an.', payHintYearly:'Sende eine einmalige Überweisung mindestens 3 Tage vor Ablauf des Abos. Vor der nächsten Verlängerung erinnert dich die App. Gib im Verwendungszweck immer den Firmencode an.', perYear:'Jahr', subUntil:'Abo gültig bis', subEndsIn:'Abo endet in {n} {d} — bitte verlängern', dayForms:{one:'Tag',other:'Tagen'}, subEndsToday:'Abo endet heute — bitte verlängern', lockedTitle:'Abo abgelaufen', lockedBody:'Der Zugang zur App ist pausiert, weil das Abo abgelaufen ist. Schreib oder ruf an, wir verlängern es sofort — deine Daten bleiben gespeichert.',
  details:'Details',
  atWork:'Im Dienst', hoursToday:'Stunden heute', costToday:'Kosten heute',
  atWorkNames:'Im Dienst', nobodyAtWork:'Niemand ist im Dienst',
  arrive:'Kommen', leave:'Gehen', arrived:'Kommen', left:'Gehen',
  atWorkSince:'Im Dienst seit', shiftNotStarted:'Schicht hat noch nicht begonnen', doneLbl:'Fertig',
  breakStart:'Pause', breakEnd:'Pause beenden', onBreakSince:'In Pause seit',
  breaksLbl:'Pausen', breakTotal:'Pausen gesamt', noBreaks:'Keine Pausen',
  addBreak:'Pause hinzufügen', netWorked:'Nettozeit', grossTime:'Anwesend',
  recorded:'Erfasst', undo:'Rückgängig', fix:'Korrigieren', fixTimes:'Zeit korrigieren',
  fixHelp:'Falls das Klicken vergessen wurde, hier die Zeit überschreiben.', clearDeparture:'Gehen löschen',
  total:'Gesamt', hours:'Stunden', cost:'Lohnkosten', monthTotal:'Monat gesamt',
  noRecord:'Kein Eintrag', legendHours:'Zahlen in den Tagen = geleistete Stunden aller zusammen',
  hUnit:'Std.', minUnit:'Min.',
  thisWeek:'Diese Woche', lastWeek:'Letzte Woche', nextWeek:'Nächste Woche',
  todayChip:'HEUTE', nobody:'niemand', planLbl:'Plan', workedLbl:'Gearbeitet',
  tapDay:'Tippe auf einen Tag, um ihn zu ändern', removeShift:'Entfernen',
  planShift:'Schicht planen', addShift:'Schicht hinzufügen', noShifts:'Keine Schichten',
  noShiftsToday:'Für heute ist keine Schicht geplant.',
  whichShift:'Welche Schicht?', morningS:'Früh', afternoonS:'Mittag', eveningS:'Abend', otherTime:'Andere Zeit',
  person:'Mitarbeiter', date:'Datum', from:'Von', to:'Bis',
  addPerson:'Mitarbeiter hinzufügen', name:'Name', rate:'Stundenlohn', noPeople:'Du hast noch keine Mitarbeiter.',
  confirmRemovePerson:'Diesen Mitarbeiter samt Schichten entfernen?',
  lastLogin:'Zuletzt angemeldet', neverLoggedIn:'Noch nie angemeldet', loggedInNow:'Jetzt angemeldet',
  loginsTitle:'Anmeldungen der Mitarbeiter', codeLbl:'Code',
  myShifts:'Meine Schichten', myHours:'Meine Stunden', gross:'Brutto',
  remove:'Entfernen', cancel:'Abbrechen', save:'Speichern',
  saved:'Gespeichert', added:'Hinzugefügt', removed:'Entfernt',
  nameRequired:'Name eingeben.', pickPerson:'Mitarbeiter wählen.', badTime:'Gehen muss nach Kommen liegen.',
  tooLong:'Die Schicht wäre über 16 Stunden lang — Zeit prüfen.',
  plannedTime:'Geplante Zeit',
  breakDetail:'Pausen (von – bis)',
  changePerson:'Person ändern',
  whoRecords:'Wer erfasst die Zeiten',
  modeOwner:'Nur ich',
  modeSelf:'Auch die Mitarbeiter selbst',
  modeHint:'Bei „Nur ich“ erfasst du Kommen und Gehen. Bei der zweiten Option erfasst es jeder selbst auf seinem Handy.',
  readOnlyNote:'Die Zeiten erfasst der Inhaber',
  todayLbl:'Heute',
  unplanned:'Ohne Plan',
  notScheduled:'Heute nicht eingeplant',
  startNow:'Jetzt kommen',
  alreadyOn:'Ist bereits im Dienst',
  planWeek:'Woche planen',
  pickDays:'Welche Tage?',
  noDays:'Wähle mindestens einen Tag.',
  createdN:'Geplante Schichten: ',
  allHaveShift:'Alle haben schon eine Schicht',
  badBreak:'Die Pause muss innerhalb der Schicht liegen.',
  signUp:'Konto erstellen', backToSignin:'Zurück zur Anmeldung',
  noAccountYet:'Noch kein Konto?', haveAccountYet:'Schon ein Konto?',
  confirmPass:'Passwort wiederholen', passMismatch:'Die Passwörter stimmen nicht überein.',
  passTooShort:'Das Passwort muss mindestens 6 Zeichen haben.',
  checkEmailTitle:'E-Mail prüfen',
  checkEmailMsg:'Wir haben einen Bestätigungslink an deine E-Mail gesendet. Klicke ihn an und melde dich dann an.',
  joinTitle:'Du trittst dem Team bei', joinName:'Dein Name', joinBtn:'Beitreten',
  joinBadCode:'Dieser Einladungslink ist nicht mehr gültig. Frag den Inhaber nach einem neuen.',
  joinDone:'Fertig, du bist beigetreten!',
  inviteHint:'Teile diesen Link mit der neuen Person – sie tritt selbst bei, du musst sie nicht manuell hinzufügen.',
  copyLink:'Link kopieren', linkCopied:'Link kopiert', newInviteCode:'Neuer Code',
  regenConfirm:'Neuen Einladungslink erzeugen? Der alte funktioniert dann nicht mehr.',
  reconnecting:'Verbindung wird wiederhergestellt…',
  unclosedShifts:'Offene Schichten aus der Vergangenheit', unclosedSince:'offen seit'
},

/* ---------------- ENGLISH ---------------- */
en:{ label:'English', locale:'en-GB', cur:'€',
  dows:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  months:['January','February','March','April','May','June','July','August','September','October','November','December'],
  dayNames:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
  tagline:'Shift and attendance tracking', language:'Language',
  installApp:'Download app', installHint:'In Chrome/Edge, click the install icon in the address bar and choose "Install".', installHintIOS:'In Safari, tap Share (square with arrow) then "Add to Home Screen".',
  yourPlan:'Your plan', peopleUsageLbl:'employees', planFreeShort:'Free', planCustomShort:'Custom', perMonth:'month', viewPricing:'Pricing', planUpTo:'Up to', planCustomRange:'Over 20 employees', planOver:'Over', limitWarn:"You've reached your plan's limit.", limitReachedBody:'This plan allows only a limited number of employees. Pick a higher plan below.', pricingTitle:'Pricing', pricingContact:'Payment runs securely through Stripe — the app never sees your card details.', contactCta:'Contact us', upgradeMailSubject:'Upgrade my Turno plan', upgradeMailBody:"Hi, I'd like to upgrade my Turno plan to add more employees.", upgradeBtn:'Choose plan', currentPlanLbl:'Current plan', manageSubBtn:'Manage subscription', checkoutRedirect:'Redirecting to payment…', checkoutSuccessMsg:'Payment successful! Your plan will update shortly.', checkoutCancelMsg:'Payment was cancelled.', noSubMsg:"You don't have a paid plan yet.", checkoutErrMsg:'Could not start checkout. Please try again.',
  owner:'Owner', employee:'Employee', imEmployee:"I'm an employee", imOwner:"I'm the owner",
  email:'Email', password:'Password', signin:'Sign in', signout:'Sign out',
  code:'Employee code', enter:'Enter', demoEnter:'Try the demo',
  demoNote:'Demo mode: data lives in memory only and resets when you reload the page.',
  liveNote:'Connected to the database.',
  badLogin:'Wrong email or password.', badCode:'No such code.',
  tabToday:'Today', tabPlan2:'Plan', tabHist:'History', tabNotes:'Notes', tabPeople:'People',
  addNote:'Add item', noteTitle:'Name', noteDetails:'Details', price:'Price', editNote:'Edit item', noNotes:"No notes yet. Add something like tomorrow's order.", costTrend:'Shift cost trend', last14days:'last 14 days', supportTitle:'Need help?', supportBody:"If something's not working or you have a question, message or call the app's developer directly.", supportEmail:'Send email', lockedEmpBody:"Access to the app is paused because the company's subscription has expired. Contact your employer — your data stays saved.", payHow:'How to renew', payMonthly:'Monthly', payYearly:'Yearly', yearlyBonus:'Pay yearly and get 2 months free.', payRecipient:'Recipient', payIban:'IBAN', payAmount:'Amount', payNote:'Payment reference', copyIban:'Copy IBAN', ibanCopied:'IBAN copied', payHintMonthly:'Set up a standing order at your bank for this amount, repeating monthly — the payment will not renew on its own. Send the first transfer at least 3 days before your subscription ends so I can record it. Always put your company code in the reference.', payHintYearly:'Send a one-off transfer at least 3 days before your subscription ends. The app will remind you before the next renewal. Always put your company code in the reference.', perYear:'year', subUntil:'Subscription valid until', subEndsIn:'Subscription ends in {n} {d} — please renew', dayForms:{one:'day',other:'days'}, subEndsToday:'Subscription ends today — please renew', lockedTitle:'Subscription expired', lockedBody:'Access to the app is paused because your subscription has expired. Message or call and we’ll renew it right away — your data stays saved.',
  details:'Details',
  atWork:'On shift', hoursToday:'Hours today', costToday:'Cost today',
  atWorkNames:'On shift', nobodyAtWork:'Nobody is on shift',
  arrive:'Clock in', leave:'Clock out', arrived:'In', left:'Out',
  atWorkSince:'On shift since', shiftNotStarted:'Shift has not started yet', doneLbl:'Done',
  breakStart:'Break', breakEnd:'End break', onBreakSince:'On break since',
  breaksLbl:'Breaks', breakTotal:'Breaks total', noBreaks:'No breaks',
  addBreak:'Add a break', netWorked:'Net time', grossTime:'On site',
  recorded:'Recorded', undo:'Undo', fix:'Fix', fixTimes:'Fix the times',
  fixHelp:'If someone forgot to tap, rewrite the time here.', clearDeparture:'Clear clock-out',
  total:'Total', hours:'Hours', cost:'Wage cost', monthTotal:'Month total',
  noRecord:'No record', legendHours:'Numbers on days = hours worked by everyone combined',
  hUnit:'h', minUnit:'min',
  thisWeek:'This week', lastWeek:'Last week', nextWeek:'Next week',
  todayChip:'TODAY', nobody:'nobody', planLbl:'Planned', workedLbl:'Worked',
  tapDay:'Tap a day to edit it', removeShift:'Remove',
  planShift:'Schedule a shift', addShift:'Add a shift', noShifts:'No shifts',
  noShiftsToday:'No shift is scheduled for today.',
  whichShift:'Which shift?', morningS:'Morning', afternoonS:'Afternoon', eveningS:'Evening', otherTime:'Other time',
  person:'Employee', date:'Date', from:'From', to:'To',
  addPerson:'Add an employee', name:'Name', rate:'Hourly rate', noPeople:'You have no employees yet.',
  confirmRemovePerson:'Remove this employee along with their shifts?',
  lastLogin:'Last signed in', neverLoggedIn:'Has not signed in yet', loggedInNow:'Signed in now',
  loginsTitle:'Employee sign-ins', codeLbl:'Code',
  myShifts:'My shifts', myHours:'My hours', gross:'Gross',
  remove:'Remove', cancel:'Cancel', save:'Save',
  saved:'Saved', added:'Added', removed:'Removed',
  nameRequired:'Enter a name.', pickPerson:'Pick an employee.', badTime:'Clock-out must be after clock-in.',
  tooLong:'That shift would be over 16 hours — check the times.',
  plannedTime:'Planned time',
  breakDetail:'Breaks (from – to)',
  changePerson:'Change person',
  whoRecords:'Who records the times',
  modeOwner:'Only me',
  modeSelf:'Employees themselves too',
  modeHint:'With \"Only me\" you tap clock-in and clock-out. With the second option each person records it on their own phone.',
  readOnlyNote:'The owner records the times',
  todayLbl:'Today',
  unplanned:'No plan',
  notScheduled:'Not scheduled today',
  startNow:'Clock in now',
  alreadyOn:'Already on shift',
  planWeek:'Plan the week',
  pickDays:'Which days?',
  noDays:'Pick at least one day.',
  createdN:'Shifts created: ',
  allHaveShift:'Everyone already has a shift',
  badBreak:'The break must fall inside the shift.',
  signUp:'Create account', backToSignin:'Back to sign in',
  noAccountYet:"Don't have an account yet?", haveAccountYet:'Already have an account?',
  confirmPass:'Repeat password', passMismatch:'Passwords do not match.',
  passTooShort:'Password must be at least 6 characters.',
  checkEmailTitle:'Check your email',
  checkEmailMsg:'We sent a confirmation link to your email. Click it, then sign in.',
  joinTitle:"You're joining the team", joinName:'Your name', joinBtn:'Join',
  joinBadCode:'This invite link no longer works. Ask the owner for a new one.',
  joinDone:"Done, you're in!",
  inviteHint:'Share this link with a new person – they join themselves, no need to add them by hand.',
  copyLink:'Copy link', linkCopied:'Link copied', newInviteCode:'New code',
  regenConfirm:'Generate a new invite link? The old one will stop working.',
  reconnecting:'Reconnecting…',
  unclosedShifts:'Unclosed shifts from the past', unclosedSince:'still open since'
},

/* ---------------- HRVATSKI ---------------- */
hr:{ label:'Hrvatski', locale:'hr-HR', cur:'€',
  dows:['Po','Ut','Sr','Če','Pe','Su','Ne'],
  months:['Siječanj','Veljača','Ožujak','Travanj','Svibanj','Lipanj','Srpanj','Kolovoz','Rujan','Listopad','Studeni','Prosinac'],
  dayNames:['Nedjelja','Ponedjeljak','Utorak','Srijeda','Četvrtak','Petak','Subota'],
  tagline:'Evidencija smjena i dolazaka', language:'Jezik',
  installApp:'Preuzmi aplikaciju', installHint:'U Chromeu/Edgeu klikni ikonu instalacije u adresnoj traci i odaberi „Instaliraj”.', installHintIOS:'U Safariju dodirni Podijeli (□↑), zatim „Dodaj na početni zaslon”.',
  yourPlan:'Tvoj plan', peopleUsageLbl:'zaposlenika', planFreeShort:'Besplatno', planCustomShort:'Individualno', perMonth:'mjesec', viewPricing:'Cjenik', planUpTo:'Do', planCustomRange:'Preko 20 zaposlenika', planOver:'Preko', limitWarn:'Dosegao si limit svog plana.', limitReachedBody:'Na ovom planu možeš imati samo ograničen broj zaposlenika. Odaberi viši plan ispod.', pricingTitle:'Cjenik', pricingContact:'Plaćanje se odvija sigurno putem Stripea — aplikacija nikad ne vidi podatke tvoje kartice.', contactCta:'Javi nam se', upgradeMailSubject:'Nadogradnja Turno plana', upgradeMailBody:'Bok, želim nadograditi svoj Turno plan za više zaposlenika.', upgradeBtn:'Odaberi plan', currentPlanLbl:'Trenutni plan', manageSubBtn:'Upravljaj pretplatom', checkoutRedirect:'Preusmjeravam na plaćanje…', checkoutSuccessMsg:'Plaćanje uspješno! Plan će se uskoro ažurirati.', checkoutCancelMsg:'Plaćanje je otkazano.', noSubMsg:'Još nemaš plaćeni plan.', checkoutErrMsg:'Plaćanje se nije uspjelo pokrenuti. Pokušaj ponovno.',
  owner:'Vlasnik', employee:'Zaposlenik', imEmployee:'Ja sam zaposlenik', imOwner:'Ja sam vlasnik',
  email:'E-mail', password:'Lozinka', signin:'Prijavi se', signout:'Odjava',
  code:'Kod zaposlenika', enter:'Ulaz', demoEnter:'Isprobaj demo',
  demoNote:'Demo način: podaci su samo u memoriji i nakon osvježavanja vraćaju se na početak.',
  liveNote:'Povezano s bazom podataka.',
  badLogin:'Netočan e-mail ili lozinka.', badCode:'Taj kod ne postoji.',
  tabToday:'Danas', tabPlan2:'Raspored', tabHist:'Povijest', tabNotes:'Bilješke', tabPeople:'Ljudi',
  addNote:'Dodaj stavku', noteTitle:'Naziv', noteDetails:'Detalji', price:'Cijena', editNote:'Uredi stavku', noNotes:'Još nema bilješki. Dodaj npr. narudžbu za sutra.', costTrend:'Kretanje troškova smjena', last14days:'za posljednjih 14 dana', supportTitle:'Trebaš pomoć?', supportBody:'Ako nešto ne radi ili imaš pitanje, javi se ili nazovi izravno tvorca aplikacije.', supportEmail:'Pošalji e-mail', lockedEmpBody:'Pristup aplikaciji je pauziran jer je pretplata tvrtke istekla. Javi se svom poslodavcu — tvoji podaci ostaju sačuvani.', payHow:'Kako obnoviti pretplatu', payMonthly:'Mjesečno', payYearly:'Godišnje', yearlyBonus:'Uz godišnje plaćanje 2 mjeseca gratis.', payRecipient:'Primatelj', payIban:'IBAN', payAmount:'Iznos', payNote:'Opis plaćanja', copyIban:'Kopiraj IBAN', ibanCopied:'IBAN kopiran', payHintMonthly:'Postavi u banci trajni nalog na ovaj iznos s mjesečnim ponavljanjem — plaćanje se samo neće obnoviti. Prvu uplatu pošalji barem 3 dana prije isteka pretplate da je stignem evidentirati. U opis plaćanja uvijek upiši šifru tvrtke.', payHintYearly:'Pošalji jednokratnu uplatu barem 3 dana prije isteka pretplate. Prije sljedeće obnove aplikacija će te podsjetiti. U opis plaćanja uvijek upiši šifru tvrtke.', perYear:'godina', subUntil:'Pretplata vrijedi do', subEndsIn:'Pretplata istječe za {n} {d} — obnovi plaćanje', dayForms:{one:'dan',few:'dana',other:'dana'}, subEndsToday:'Pretplata istječe danas — obnovi plaćanje', lockedTitle:'Pretplata je istekla', lockedBody:'Pristup aplikaciji je pauziran jer je pretplata istekla. Javi se ili nazovi i odmah ćemo je obnoviti — tvoji podaci ostaju sačuvani.',
  details:'Detalji',
  atWork:'Na radu', hoursToday:'Sati danas', costToday:'Trošak danas',
  atWorkNames:'Na radu', nobodyAtWork:'Nitko nije na radu',
  arrive:'Dolazak', leave:'Odlazak', arrived:'Dolazak', left:'Odlazak',
  atWorkSince:'Na radu od', shiftNotStarted:'Smjena još nije počela', doneLbl:'Gotovo',
  breakStart:'Pauza', breakEnd:'Kraj pauze', onBreakSince:'Na pauzi od',
  breaksLbl:'Pauze', breakTotal:'Pauze ukupno', noBreaks:'Nema pauza',
  addBreak:'Dodaj pauzu', netWorked:'Neto vrijeme', grossTime:'Na radnom mjestu',
  recorded:'Zapisano', undo:'Vrati', fix:'Ispravi', fixTimes:'Ispravi vrijeme',
  fixHelp:'Ako se zaboravilo kliknuti, prepiši vrijeme ovdje.', clearDeparture:'Izbriši odlazak',
  total:'Ukupno', hours:'Sati', cost:'Trošak plaća', monthTotal:'Mjesec ukupno',
  noRecord:'Nema zapisa', legendHours:'Brojevi u danima = odrađeni sati svih zajedno',
  hUnit:'h', minUnit:'min',
  thisWeek:'Ovaj tjedan', lastWeek:'Prošli tjedan', nextWeek:'Sljedeći tjedan',
  todayChip:'DANAS', nobody:'nitko', planLbl:'Plan', workedLbl:'Odrađeno',
  tapDay:'Dotakni dan za uređivanje', removeShift:'Ukloni',
  planShift:'Zakaži smjenu', addShift:'Dodaj smjenu', noShifts:'Nema smjena',
  noShiftsToday:'Za danas nema zakazane smjene.',
  whichShift:'Koja smjena?', morningS:'Jutarnja', afternoonS:'Poslijepodnevna', eveningS:'Večernja', otherTime:'Drugo vrijeme',
  person:'Zaposlenik', date:'Datum', from:'Od', to:'Do',
  addPerson:'Dodaj zaposlenika', name:'Ime', rate:'Satnica', noPeople:'Još nemaš zaposlenika.',
  confirmRemovePerson:'Ukloniti ovog zaposlenika zajedno s njegovim smjenama?',
  lastLogin:'Zadnja prijava', neverLoggedIn:'Još se nije prijavio', loggedInNow:'Prijavljen sada',
  loginsTitle:'Prijave zaposlenika', codeLbl:'Kod',
  myShifts:'Moje smjene', myHours:'Moji sati', gross:'Bruto',
  remove:'Ukloni', cancel:'Otkaži', save:'Sačuvaj',
  saved:'Sačuvano', added:'Dodano', removed:'Uklonjeno',
  nameRequired:'Unesi ime.', pickPerson:'Odaberi zaposlenika.', badTime:'Odlazak mora biti nakon dolaska.',
  tooLong:'Smjena bi trajala 16+ sati — provjeri vrijeme.',
  plannedTime:'Planirano vrijeme',
  breakDetail:'Pauze (od – do)',
  changePerson:'Promijeni osobu',
  whoRecords:'Kto upisuje dolaske',
  modeOwner:'Samo ja',
  modeSelf:'I zaposlenici sami',
  modeHint:'Kod „Samo ja“ dolaske i odlaske klikaš ti. Kod druge opcije svatko ih upisuje sam na svom telefonu.',
  readOnlyNote:'Dolaske upisuje vlasnik',
  todayLbl:'Danas',
  unplanned:'Bez plana',
  notScheduled:'Danas nisu u rasporedu',
  startNow:'Dolazak sada',
  alreadyOn:'Već je na radu',
  planWeek:'Planiraj tjedan',
  pickDays:'Koji dani?',
  noDays:'Odaberi barem jedan dan.',
  createdN:'Zakazane smjene: ',
  allHaveShift:'Svi već imaju smjenu',
  badBreak:'Pauza mora biti unutar smjene.',
  signUp:'Napravi račun', backToSignin:'Natrag na prijavu',
  noAccountYet:'Nemaš još račun?', haveAccountYet:'Već imaš račun?',
  confirmPass:'Ponovi lozinku', passMismatch:'Lozinke se ne podudaraju.',
  passTooShort:'Lozinka mora imati najmanje 6 znakova.',
  checkEmailTitle:'Provjeri e-poštu',
  checkEmailMsg:'Poslali smo potvrdni link na tvoju e-poštu. Klikni ga, pa se prijavi.',
  joinTitle:'Pridružuješ se timu', joinName:'Tvoje ime', joinBtn:'Pridruži se',
  joinBadCode:'Ovaj pozivni link više ne vrijedi. Zamoli vlasnika za novi.',
  joinDone:'Gotovo, pridružio/la si se!',
  inviteHint:'Podijeli ovaj link s novom osobom – pridružit će se sama, ne moraš je dodavati ručno.',
  copyLink:'Kopiraj link', linkCopied:'Link kopiran', newInviteCode:'Novi kod',
  regenConfirm:'Generirati novi pozivni link? Stari više neće raditi.',
  reconnecting:'Obnavljam vezu…',
  unclosedShifts:'Nezatvorene smjene iz prošlosti', unclosedSince:'nezatvorena od'
},

/* ---------------- БЪЛГАРСКИ ---------------- */
bg:{ label:'Български', locale:'bg-BG', cur:'€',
  dows:['Пн','Вт','Ср','Чт','Пт','Сб','Нд'],
  months:['Януари','Февруари','Март','Април','Май','Юни','Юли','Август','Септември','Октомври','Ноември','Декември'],
  dayNames:['Неделя','Понеделник','Вторник','Сряда','Четвъртък','Петък','Събота'],
  tagline:'Отчитане на смени и присъствие', language:'Език',
  installApp:'Изтегли приложението', installHint:'В Chrome/Edge кликни иконата за инсталиране в адресната лента и избери „Инсталирай“.', installHintIOS:'В Safari докосни Сподели (□↑), после „Добави към начален екран“.',
  yourPlan:'Твоят план', peopleUsageLbl:'служители', planFreeShort:'Безплатно', planCustomShort:'Индивидуално', perMonth:'месец', viewPricing:'Цени', planUpTo:'До', planCustomRange:'Над 20 служители', planOver:'Над', limitWarn:'Достигна лимита на своя план.', limitReachedBody:'На този план можеш да имаш само ограничен брой служители. Избери по-висок план по-долу.', pricingTitle:'Цени', pricingContact:'Плащането се извършва сигурно през Stripe — приложението никога не вижда данните на картата ти.', contactCta:'Пиши ни', upgradeMailSubject:'Надграждане на Turno плана', upgradeMailBody:'Здравей, искам да надградя своя Turno план за повече служители.', upgradeBtn:'Избери план', currentPlanLbl:'Текущ план', manageSubBtn:'Управление на абонамента', checkoutRedirect:'Пренасочване към плащане…', checkoutSuccessMsg:'Плащането е успешно! Планът ще се обнови скоро.', checkoutCancelMsg:'Плащането беше отказано.', noSubMsg:'Все още нямаш платен план.', checkoutErrMsg:'Плащането не можа да стартира. Опитай отново.',
  owner:'Собственик', employee:'Служител', imEmployee:'Аз съм служител', imOwner:'Аз съм собственик',
  email:'Имейл', password:'Парола', signin:'Вход', signout:'Изход',
  code:'Код на служителя', enter:'Влез', demoEnter:'Пробвай демото',
  demoNote:'Демо режим: данните са само в паметта и се връщат в начално състояние при презареждане.',
  liveNote:'Свързано с базата данни.',
  badLogin:'Грешен имейл или парола.', badCode:'Такъв код не съществува.',
  tabToday:'Днес', tabPlan2:'График', tabHist:'История', tabNotes:'Бележки', tabPeople:'Хора',
  addNote:'Добави артикул', noteTitle:'Наименование', noteDetails:'Подробности', price:'Цена', editNote:'Редактирай артикул', noNotes:'Все още няма бележки. Добави например поръчка за утре.', costTrend:'Тенденция на разходите за смени', last14days:'за последните 14 дни', supportTitle:'Нуждаеш се от помощ?', supportBody:'Ако нещо не работи или имаш въпрос, пиши или се обади директно на създателя на приложението.', supportEmail:'Изпрати имейл', lockedEmpBody:'Достъпът до приложението е спрян, защото абонаментът на фирмата е изтекъл. Свържи се с работодателя си — данните ти остават запазени.', payHow:'Как да подновиш абонамента', payMonthly:'Месечно', payYearly:'Годишно', yearlyBonus:'При годишно плащане 2 месеца безплатно.', payRecipient:'Получател', payIban:'IBAN', payAmount:'Сума', payNote:'Основание за плащане', copyIban:'Копирай IBAN', ibanCopied:'IBAN е копиран', payHintMonthly:'Настрой в банката си периодичен превод за тази сума с месечно повторение — плащането няма да се поднови само. Изпрати първия превод поне 3 дни преди края на абонамента, за да успея да го отчета. В основанието винаги посочвай кода на фирмата.', payHintYearly:'Изпрати еднократен превод поне 3 дни преди края на абонамента. Преди следващото подновяване приложението ще ти напомни. В основанието винаги посочвай кода на фирмата.', perYear:'година', subUntil:'Абонаментът важи до', subEndsIn:'Абонаментът изтича след {n} {d} — поднови плащането', dayForms:{one:'ден',other:'дни'}, subEndsToday:'Абонаментът изтича днес — поднови плащането', lockedTitle:'Абонаментът изтече', lockedBody:'Достъпът до приложението е спрян, защото абонаментът е изтекъл. Пиши или се обади и веднага ще го подновим — данните ти остават запазени.',
  details:'Подробности',
  atWork:'На работа', hoursToday:'Часове днес', costToday:'Разход днес',
  atWorkNames:'На работа', nobodyAtWork:'Никой не е на работа',
  arrive:'Идване', leave:'Тръгване', arrived:'Идване', left:'Тръгване',
  atWorkSince:'На работа от', shiftNotStarted:'Смяната още не е започнала', doneLbl:'Готово',
  breakStart:'Почивка', breakEnd:'Край на почивката', onBreakSince:'В почивка от',
  breaksLbl:'Почивки', breakTotal:'Почивки общо', noBreaks:'Няма почивки',
  addBreak:'Добави почивка', netWorked:'Нетно време', grossTime:'На работното място',
  recorded:'Записано', undo:'Върни', fix:'Поправи', fixTimes:'Поправи часа',
  fixHelp:'Ако е забравено да се натисне, пренапиши часа тук.', clearDeparture:'Изтрий тръгването',
  total:'Общо', hours:'Часове', cost:'Разход за заплати', monthTotal:'Месец общо',
  noRecord:'Няма запис', legendHours:'Числата в дните = отработени часове на всички заедно',
  hUnit:'ч', minUnit:'мин',
  thisWeek:'Тази седмица', lastWeek:'Миналата седмица', nextWeek:'Следващата седмица',
  todayChip:'ДНЕС', nobody:'никой', planLbl:'Планирано', workedLbl:'Отработено',
  tapDay:'Докосни ден, за да го редактираш', removeShift:'Премахни',
  planShift:'Планирай смяна', addShift:'Добави смяна', noShifts:'Няма смени',
  noShiftsToday:'За днес няма планирана смяна.',
  whichShift:'Коя смяна?', morningS:'Сутрешна', afternoonS:'Следобедна', eveningS:'Вечерна', otherTime:'Друг час',
  person:'Служител', date:'Дата', from:'От', to:'До',
  addPerson:'Добави служител', name:'Име', rate:'Часова ставка', noPeople:'Още нямаш служители.',
  confirmRemovePerson:'Да премахна ли този служител заедно със смените му?',
  lastLogin:'Последен вход', neverLoggedIn:'Още не е влизал', loggedInNow:'Влязъл сега',
  loginsTitle:'Влизания на служителите', codeLbl:'Код',
  myShifts:'Моите смени', myHours:'Моите часове', gross:'Бруто',
  remove:'Премахни', cancel:'Отказ', save:'Запази',
  saved:'Запазено', added:'Добавено', removed:'Премахнато',
  nameRequired:'Въведи име.', pickPerson:'Избери служител.', badTime:'Тръгването трябва да е след идването.',
  tooLong:'Смяната би била 16+ часа — провери часа.',
  plannedTime:'Планирано време',
  breakDetail:'Почивки (от – до)',
  changePerson:'Смени човека',
  whoRecords:'Кой записва идванията',
  modeOwner:'Само аз',
  modeSelf:'И служителите сами',
  modeHint:'При „Само аз“ идванията и тръгванията отбелязваш ти. При втората опция всеки ги записва сам на своя телефон.',
  readOnlyNote:'Идванията записва собственикът',
  todayLbl:'Днес',
  unplanned:'Без план',
  notScheduled:'Днес не са в графика',
  startNow:'Идване сега',
  alreadyOn:'Вече е на работа',
  planWeek:'Планирай седмицата',
  pickDays:'Кои дни?',
  noDays:'Избери поне един ден.',
  createdN:'Планирани смени: ',
  allHaveShift:'Всички вече имат смяна',
  badBreak:'Почивката трябва да е в рамките на смяната.',
  signUp:'Създай акаунт', backToSignin:'Назад към вход',
  noAccountYet:'Нямаш акаунт?', haveAccountYet:'Вече имаш акаунт?',
  confirmPass:'Паролата отново', passMismatch:'Паролите не съвпадат.',
  passTooShort:'Паролата трябва да е поне 6 символа.',
  checkEmailTitle:'Провери имейла си',
  checkEmailMsg:'Изпратихме потвърждаващ линк на имейла ти. Кликни го и после влез.',
  joinTitle:'Присъединяваш се към екипа', joinName:'Твоето име', joinBtn:'Присъедини се',
  joinBadCode:'Тази покана вече не важи. Помоли собственика за нова.',
  joinDone:'Готово, присъедини се!',
  inviteHint:'Сподели този линк с новия човек – ще се присъедини сам, не е нужно да го добавяш ръчно.',
  copyLink:'Копирай линка', linkCopied:'Линкът е копиран', newInviteCode:'Нов код',
  regenConfirm:'Да генерирам нов линк за покана? Старият ще спре да работи.',
  reconnecting:'Възстановяване на връзката…',
  unclosedShifts:'Незатворени смени от миналото', unclosedSince:'незатворена от'
},

/* ---------------- РУССКИЙ ---------------- */
ru:{ label:'Русский', locale:'ru-RU', cur:'₽',
  dows:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],
  months:['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
  dayNames:['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'],
  tagline:'Учёт смен и посещаемости', language:'Язык',
  installApp:'Скачать приложение', installHint:'В Chrome/Edge нажми на значок установки в адресной строке и выбери «Установить».', installHintIOS:'В Safari нажми «Поделиться» (□↑), затем «На экран «Домой»».',
  yourPlan:'Твой тариф', peopleUsageLbl:'сотрудников', planFreeShort:'Бесплатно', planCustomShort:'Индивидуально', perMonth:'месяц', viewPricing:'Тарифы', planUpTo:'До', planCustomRange:'Более 20 сотрудников', planOver:'Более', limitWarn:'Ты достиг лимита своего тарифа.', limitReachedBody:'На этом тарифе можно иметь лишь ограниченное число сотрудников. Выбери тариф повыше ниже.', pricingTitle:'Тарифы', pricingContact:'Оплата проходит безопасно через Stripe — приложение никогда не видит данные твоей карты.', contactCta:'Написать нам', upgradeMailSubject:'Повысить тариф Turno', upgradeMailBody:'Привет, хочу повысить свой тариф Turno, чтобы добавить больше сотрудников.', upgradeBtn:'Выбрать тариф', currentPlanLbl:'Текущий тариф', manageSubBtn:'Управление подпиской', checkoutRedirect:'Перенаправление на оплату…', checkoutSuccessMsg:'Оплата прошла успешно! Тариф скоро обновится.', checkoutCancelMsg:'Оплата отменена.', noSubMsg:'У тебя пока нет платного тарифа.', checkoutErrMsg:'Не удалось запустить оплату. Попробуй снова.',
  owner:'Владелец', employee:'Сотрудник', imEmployee:'Я сотрудник', imOwner:'Я владелец',
  email:'E-mail', password:'Пароль', signin:'Войти', signout:'Выйти',
  code:'Код сотрудника', enter:'Войти', demoEnter:'Попробовать демо',
  demoNote:'Демо-режим: данные хранятся только в памяти и сбрасываются при перезагрузке страницы.',
  liveNote:'Подключено к базе данных.',
  badLogin:'Неверный e-mail или пароль.', badCode:'Такого кода нет.',
  tabToday:'Сегодня', tabPlan2:'График', tabHist:'История', tabNotes:'Заметки', tabPeople:'Люди',
  addNote:'Добавить позицию', noteTitle:'Название', noteDetails:'Подробности', price:'Цена', editNote:'Редактировать позицию', noNotes:'Пока нет заметок. Добавь, например, заказ на завтра.', costTrend:'Динамика расходов на смены', last14days:'за последние 14 дней', supportTitle:'Нужна помощь?', supportBody:'Если что-то не работает или есть вопрос, напиши или позвони прямо создателю приложения.', supportEmail:'Написать письмо', lockedEmpBody:'Доступ к приложению приостановлен, так как подписка компании истекла. Свяжись со своим работодателем — твои данные сохраняются.', payHow:'Как продлить подписку', payMonthly:'Ежемесячно', payYearly:'Ежегодно', yearlyBonus:'При годовой оплате 2 месяца бесплатно.', payRecipient:'Получатель', payIban:'IBAN', payAmount:'Сумма', payNote:'Назначение платежа', copyIban:'Копировать IBAN', ibanCopied:'IBAN скопирован', payHintMonthly:'Настрой в банке регулярный платёж на эту сумму с ежемесячным повторением — сама подписка не продлится. Первый перевод отправь минимум за 3 дня до окончания подписки, чтобы я успел его учесть. В назначении платежа всегда указывай код компании.', payHintYearly:'Отправь разовый перевод минимум за 3 дня до окончания подписки. Перед следующим продлением приложение напомнит. В назначении платежа всегда указывай код компании.', perYear:'год', subUntil:'Подписка действует до', subEndsIn:'Подписка заканчивается через {n} {d} — продли оплату', dayForms:{one:'день',few:'дня',many:'дней',other:'дня'}, subEndsToday:'Подписка заканчивается сегодня — продли оплату', lockedTitle:'Подписка истекла', lockedBody:'Доступ к приложению приостановлен, так как подписка истекла. Напиши или позвони — сразу продлим, твои данные сохраняются.',
  details:'Подробности',
  atWork:'На смене', hoursToday:'Часов сегодня', costToday:'Расход сегодня',
  atWorkNames:'На смене', nobodyAtWork:'Никого нет на смене',
  arrive:'Приход', leave:'Уход', arrived:'Приход', left:'Уход',
  atWorkSince:'На смене с', shiftNotStarted:'Смена ещё не началась', doneLbl:'Готово',
  breakStart:'Перерыв', breakEnd:'Конец перерыва', onBreakSince:'На перерыве с',
  breaksLbl:'Перерывы', breakTotal:'Перерывы всего', noBreaks:'Перерывов нет',
  addBreak:'Добавить перерыв', netWorked:'Чистое время', grossTime:'На рабочем месте',
  recorded:'Записано', undo:'Отменить', fix:'Исправить', fixTimes:'Исправить время',
  fixHelp:'Если забыли нажать, перепишите время здесь.', clearDeparture:'Удалить уход',
  total:'Всего', hours:'Часы', cost:'Расход на зарплату', monthTotal:'Месяц всего',
  noRecord:'Нет записи', legendHours:'Числа в днях = отработанные часы всех вместе',
  hUnit:'ч', minUnit:'мин',
  thisWeek:'Эта неделя', lastWeek:'Прошлая неделя', nextWeek:'Следующая неделя',
  todayChip:'СЕГОДНЯ', nobody:'никто', planLbl:'План', workedLbl:'Отработано',
  tapDay:'Нажмите на день, чтобы изменить', removeShift:'Убрать',
  planShift:'Запланировать смену', addShift:'Добавить смену', noShifts:'Смен нет',
  noShiftsToday:'На сегодня смен не запланировано.',
  whichShift:'Какая смена?', morningS:'Утренняя', afternoonS:'Дневная', eveningS:'Вечерняя', otherTime:'Другое время',
  person:'Сотрудник', date:'Дата', from:'С', to:'До',
  addPerson:'Добавить сотрудника', name:'Имя', rate:'Ставка в час', noPeople:'У вас пока нет сотрудников.',
  confirmRemovePerson:'Удалить этого сотрудника вместе с его сменами?',
  lastLogin:'Последний вход', neverLoggedIn:'Ещё не входил', loggedInNow:'В сети сейчас',
  loginsTitle:'Входы сотрудников', codeLbl:'Код',
  myShifts:'Мои смены', myHours:'Мои часы', gross:'Брутто',
  remove:'Удалить', cancel:'Отмена', save:'Сохранить',
  saved:'Сохранено', added:'Добавлено', removed:'Удалено',
  nameRequired:'Введите имя.', pickPerson:'Выберите сотрудника.', badTime:'Уход должен быть позже прихода.',
  tooLong:'Смена вышла бы 16+ часов — проверьте время.',
  plannedTime:'Плановое время',
  breakDetail:'Перерывы (с – до)',
  changePerson:'Сменить человека',
  whoRecords:'Кто отмечает время',
  modeOwner:'Только я',
  modeSelf:'И сотрудники сами',
  modeHint:'При «Только я» приход и уход отмечаете вы. При втором варианте каждый отмечает сам на своём телефоне.',
  readOnlyNote:'Время отмечает владелец',
  todayLbl:'Сегодня',
  unplanned:'Без плана',
  notScheduled:'Сегодня не в графике',
  startNow:'Приход сейчас',
  alreadyOn:'Уже на смене',
  planWeek:'Запланировать неделю',
  pickDays:'Какие дни?',
  noDays:'Выберите хотя бы один день.',
  createdN:'Создано смен: ',
  allHaveShift:'У всех уже есть смена',
  badBreak:'Перерыв должен быть внутри смены.',
  signUp:'Создать аккаунт', backToSignin:'Назад ко входу',
  noAccountYet:'Ещё нет аккаунта?', haveAccountYet:'Уже есть аккаунт?',
  confirmPass:'Повторите пароль', passMismatch:'Пароли не совпадают.',
  passTooShort:'Пароль должен быть не менее 6 символов.',
  checkEmailTitle:'Проверьте почту',
  checkEmailMsg:'Мы отправили ссылку для подтверждения на вашу почту. Перейдите по ней, затем войдите.',
  joinTitle:'Вы присоединяетесь к команде', joinName:'Ваше имя', joinBtn:'Присоединиться',
  joinBadCode:'Эта ссылка-приглашение больше не действует. Попросите у владельца новую.',
  joinDone:'Готово, вы присоединились!',
  inviteHint:'Поделитесь этой ссылкой с новым человеком — он присоединится сам, добавлять вручную не нужно.',
  copyLink:'Скопировать ссылку', linkCopied:'Ссылка скопирована', newInviteCode:'Новый код',
  regenConfirm:'Создать новую ссылку-приглашение? Старая перестанет работать.',
  reconnecting:'Восстановление соединения…',
  unclosedShifts:'Незакрытые смены из прошлого', unclosedSince:'не закрыта с'
}

};
